var $S;function $Saa(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}}function $Sa(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return d?d.call(a):{next:$Saa(a)}}function $Sba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<a.length;++d){var e=a[d];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");}
var $Sb=$Sba(this),$Sc="function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,e){if(a==Array.prototype||a==Object.prototype)return a;a[d]=e.value;return a};function $Sd(a,d){if(d){var e=$Sb;a=a.split(".");for(var f=0;f<a.length-1;f++){var h=a[f];h in e||(e[h]={});e=e[h]}a=a[a.length-1];f=e[a];d=d(f);d!=f&&null!=d&&$Sc(e,a,{configurable:!0,writable:!0,value:d})}}
$Sd("Promise",function(a){function d(m){this.g=0;this.N=void 0;this.b=[];var v=this.l();try{m(v.resolve,v.reject)}catch(w){v.reject(w)}}function e(){this.b=null}function f(m){return m instanceof d?m:new d(function(v){v(m)})}if(a)return a;e.prototype.g=function(m){if(null==this.b){this.b=[];var v=this;this.l(function(){v.N()})}this.b.push(m)};var h=$Sb.setTimeout;e.prototype.l=function(m){h(m,0)};e.prototype.N=function(){for(;this.b&&this.b.length;){var m=this.b;this.b=[];for(var v=0;v<m.length;++v){var w=
m[v];m[v]=null;try{w()}catch(x){this.D(x)}}}this.b=null};e.prototype.D=function(m){this.l(function(){throw m;})};d.prototype.l=function(){function m(x){return function(D){w||(w=!0,x.call(v,D))}}var v=this,w=!1;return{resolve:m(this.$a),reject:m(this.D)}};d.prototype.$a=function(m){if(m===this)this.D(new TypeError("A Promise cannot resolve to itself"));else if(m instanceof d)this.bb(m);else{a:switch(typeof m){case "object":var v=null!=m;break a;case "function":v=!0;break a;default:v=!1}v?this.Ya(m):
this.Y(m)}};d.prototype.Ya=function(m){var v=void 0;try{v=m.then}catch(w){this.D(w);return}"function"==typeof v?this.hb(v,m):this.Y(m)};d.prototype.D=function(m){this.aa(2,m)};d.prototype.Y=function(m){this.aa(1,m)};d.prototype.aa=function(m,v){if(0!=this.g)throw Error("Cannot settle("+m+", "+v+"): Promise already settled in state"+this.g);this.g=m;this.N=v;this.ma()};d.prototype.ma=function(){if(null!=this.b){for(var m=0;m<this.b.length;++m)l.g(this.b[m]);this.b=null}};var l=new e;d.prototype.bb=
function(m){var v=this.l();m.pb(v.resolve,v.reject)};d.prototype.hb=function(m,v){var w=this.l();try{m.call(v,w.resolve,w.reject)}catch(x){w.reject(x)}};d.prototype.then=function(m,v){function w(y,M){return"function"==typeof y?function(k){try{x(y(k))}catch(r){D(r)}}:M}var x,D,F=new d(function(y,M){x=y;D=M});this.pb(w(m,x),w(v,D));return F};d.prototype.catch=function(m){return this.then(void 0,m)};d.prototype.pb=function(m,v){function w(){switch(x.g){case 1:m(x.N);break;case 2:v(x.N);break;default:throw Error("Unexpected state: "+
x.g);}}var x=this;null==this.b?l.g(w):this.b.push(w)};d.resolve=f;d.reject=function(m){return new d(function(v,w){w(m)})};d.race=function(m){return new d(function(v,w){for(var x=$Sa(m),D=x.next();!D.done;D=x.next())f(D.value).pb(v,w)})};d.all=function(m){var v=$Sa(m),w=v.next();return w.done?f([]):new d(function(x,D){function F(k){return function(r){y[k]=r;M--;0==M&&x(y)}}var y=[],M=0;do y.push(void 0),M++,f(w.value).pb(F(y.length-1),D),w=v.next();while(!w.done)})};return d});
function $Sca(){$Sca=function(){};$Sb.Symbol||($Sb.Symbol=$Sda)}function $Sea(a,d){this.b=a;$Sc(this,"description",{configurable:!0,writable:!0,value:d})}$Sea.prototype.toString=function(){return this.b};var $Sda=function(){function a(e){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $Sea("jscomp_symbol_"+(e||"")+"_"+d++,e)}var d=0;return a}();
function $Se(){$Sca();var a=$Sb.Symbol.iterator;a||(a=$Sb.Symbol.iterator=$Sb.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$Sc(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $Sfa($Saa(this))}});$Se=function(){}}function $Sfa(a){$Se();a={next:a};a[$Sb.Symbol.iterator]=function(){return this};return a}function $Sf(){this.Y=!1;this.l=null;this.N=void 0;this.b=1;this.ma=this.g=0;this.D=null}
function $Sg(a){if(a.Y)throw new TypeError("Generator is already running");a.Y=!0}$Sf.prototype.aa=function(a){this.N=a};function $Sh(a,d){a.D={wc:d,Rd:!0};a.b=a.g||a.ma}$Sf.prototype.return=function(a){this.D={return:a};this.b=this.ma};function $Si(a,d,e){a.b=e;return{value:d}}function $Sj(a,d){a.b=d;a.g=0}function $Sk(a){a.g=0;var d=a.D.wc;a.D=null;return d}function $Sga(a){this.b=new $Sf;this.g=a}
function $Sha(a,d){$Sg(a.b);var e=a.b.l;if(e)return $Sl(a,"return"in e?e["return"]:function(f){return{value:f,done:!0}},d,a.b.return);a.b.return(d);return $Sm(a)}function $Sl(a,d,e,f){try{var h=d.call(a.b.l,e);if(!(h instanceof Object))throw new TypeError("Iterator result "+h+" is not an object");if(!h.done)return a.b.Y=!1,h;var l=h.value}catch(m){return a.b.l=null,$Sh(a.b,m),$Sm(a)}a.b.l=null;f.call(a.b,l);return $Sm(a)}
function $Sm(a){for(;a.b.b;)try{var d=a.g(a.b);if(d)return a.b.Y=!1,{value:d.value,done:!1}}catch(e){a.b.N=void 0,$Sh(a.b,e)}a.b.Y=!1;if(a.b.D){d=a.b.D;a.b.D=null;if(d.Rd)throw d.wc;return{value:d.return,done:!0}}return{value:void 0,done:!0}}
function $Sia(a){this.next=function(d){$Sg(a.b);a.b.l?d=$Sl(a,a.b.l.next,d,a.b.aa):(a.b.aa(d),d=$Sm(a));return d};this.throw=function(d){$Sg(a.b);a.b.l?d=$Sl(a,a.b.l["throw"],d,a.b.aa):($Sh(a.b,d),d=$Sm(a));return d};this.return=function(d){return $Sha(a,d)};$Se();this[Symbol.iterator]=function(){return this}}
function $Sja(a){function d(f){return a.next(f)}function e(f){return a.throw(f)}return new Promise(function(f,h){function l(m){m.done?f(m.value):Promise.resolve(m.value).then(d,e).then(l,h)}l(a.next())})}function $Sn(a){return $Sja(new $Sia(new $Sga(a)))}$Sd("Array.prototype.find",function(a){return a?a:function(d,e){a:{var f=this;f instanceof String&&(f=String(f));for(var h=f.length,l=0;l<h;l++){var m=f[l];if(d.call(e,m,l,f)){d=m;break a}}d=void 0}return d}});
$Sd("String.prototype.endsWith",function(a){return a?a:function(d,e){if(null==this)throw new TypeError("The 'this' value for String.prototype.endsWith must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype.endsWith must not be a regular expression");void 0===e&&(e=this.length);e=Math.max(0,Math.min(e|0,this.length));for(var f=d.length;0<f&&0<e;)if(this[--e]!=d[--f])return!1;return 0>=f}});
$Sd("Array.prototype.copyWithin",function(a){function d(e){e=Number(e);return Infinity===e||-Infinity===e?e:e|0}return a?a:function(e,f,h){var l=this.length;e=d(e);f=d(f);h=void 0===h?l:d(h);e=0>e?Math.max(l+e,0):Math.min(e,l);f=0>f?Math.max(l+f,0):Math.min(f,l);h=0>h?Math.max(l+h,0):Math.min(h,l);if(e<f)for(;f<h;)f in this?this[e++]=this[f++]:(delete this[e++],f++);else for(h=Math.min(h,l+f-e),e+=h-f;h>f;)--h in this?this[--e]=this[h]:delete this[--e];return this}});
function $So(a,d,e){return a.hasOwnProperty(d)?a[d]:e}function $Sp(){}
function $Ska(){var a=adapter;if(!$Sq){$Sla=$Sq=!0;$Sr=a;$Sma=function(f,h){try{f.srcObject=h}catch(l){try{f.src=URL.createObjectURL(h)}catch(m){console.log("attaching player failed")}}};$Sna=function(f,h){try{f.srcObject=h.srcObject,h.srcObject=null}catch(l){try{f.src=h.src,h.src=null}catch(m){console.log("replacing player failed")}}};$Ss=!1;$St=function(){};if("safari"===$Sr.browserDetails.browser&&605<=$Sr.browserDetails.version)if(RTCRtpSender&&RTCRtpSender.getCapabilities&&RTCRtpSender.getCapabilities("video")&&
RTCRtpSender.getCapabilities("video").codecs&&RTCRtpSender.getCapabilities("video").codecs.length){a=$Sa(RTCRtpSender.getCapabilities("video").codecs);for(var d=a.next();!d.done;d=a.next())if((d=d.value)&&d.mimeType&&"video/vp8"===d.mimeType.toLowerCase()){$Ss=!0;break}$Ss||$St()}else{var e=new RTCPeerConnection({});e.createOffer({offerToReceiveVideo:!0}).then(function(f){($Ss=-1!==f.sdp.indexOf("VP8"))||$St();e.close();e=null})}$Su=!1;if("firefox"===$Sr.browserDetails.browser&&59<=$Sr.browserDetails.version)$Su=
!0;else if("chrome"===$Sr.browserDetails.browser&&72<=$Sr.browserDetails.version)$Su=!0;else if(window.RTCRtpTransceiver&&"currentDirection"in RTCRtpTransceiver.prototype){a=new RTCPeerConnection;try{a.addTransceiver("audio"),$Su=!0}catch(f){}a.close()}else $Su=!1}}
function $Soa(a){a=a||{};a.Qc="function"==typeof a.Qc?a.Qc:$Sp;a.L="function"==typeof a.L?a.L:$Sp;a.M="function"==typeof a.M?a.M:$Sp;a.Vb="function"==typeof a.Vb?a.Vb:$Sp;a.Eb="function"==typeof a.Eb?a.Eb:$Sp;a.Db="function"==typeof a.Db?a.Db:$Sp;a.cb="function"==typeof a.cb?a.cb:$Sp;a.Aa="function"==typeof a.Aa?a.Aa:$Sp;a.Rc="function"==typeof a.Rc?a.Rc:$Sp;a.Sc="function"==typeof a.Sc?a.Sc:$Sp;a.Cb="function"==typeof a.Cb?a.Cb:$Sp;a.Qa="function"==typeof a.Qa?a.Qa:$Sp;a.Oa="function"==typeof a.Oa?
a.Oa:$Sp;a.Kb="function"==typeof a.Kb?a.Kb:$Sp;a.Pa=function(){a.L(this.e)}}
function $Sv(a,d){function e(k){var r={high:9E5,Na:5E5,low:2E5};void 0!==k&&null!==k&&(k.high&&(r.high=k.high),k.Na&&(r.Na=k.Na),k.low&&(r.low=k.low));return r}function f(k,r,n){function q(z){z=z.target.label;if("open"===(t.P[z]?t.P[z].readyState:"null")&&t.P[z].pending&&0<t.P[z].pending.length){for(var G=$Sa(t.P[z].pending),A=G.next();!A.done;A=G.next())t.P[z].send(A.value);t.P[z].pending=[]}}var t=this.U;t.P[k]=r?r:t.c.createDataChannel(k,{ordered:!0});t.P[k].onmessage=function(){};t.P[k].onopen=
q;t.P[k].onclose=q;t.P[k].onerror=function(){};t.P[k].pending=[];n&&t.P[k].pending.push(n)}function h(k){for(var r=k.split("\r\n"),n=!1,q=[-1],t=[-1],z=null,G=null,A=null,H=null,E=-1,C=0;C<r.length;C++){var B=r[C].match(/m=(\w+) */);if(B)if(B=B[1],"video"===B)if(0>q[0])n=!0;else{E=C;break}else{if(-1<q[0]){E=C;break}}else if(n)if(B=r[C].match(/a=ssrc-group:FID (\d+) (\d+)/))q[0]=B[1],t[0]=B[2],r.splice(C,1),C--;else{if(q[0]){(B=r[C].match("a=ssrc:"+q[0]+" cname:(.+)"))&&(z=B[1]);(B=r[C].match("a=ssrc:"+
q[0]+" msid:(.+)"))&&(G=B[1]);(B=r[C].match("a=ssrc:"+q[0]+" mslabel:(.+)"))&&(A=B[1]);(B=r[C].match("a=ssrc:"+q[0]+" label:(.+)"))&&(H=B[1]);if(0===r[C].indexOf("a=ssrc:"+t[0])){r.splice(C,1);C--;continue}if(0===r[C].indexOf("a=ssrc:"+q[0])){r.splice(C,1);C--;continue}}0==r[C].length&&(r.splice(C,1),C--)}}if(0>q[0])for(E=-1,n=!1,C=0;C<r.length;C++)if(B=r[C].match(/m=(\w+) */))if(B=B[1],"video"===B)if(0>q[0])n=!0;else{E=C;break}else{if(-1<q[0]){E=C;break}}else if(n){if(0>q[0]){if(B=r[C].match(/a=ssrc:(\d+)/)){q[0]=
B[1];r.splice(C,1);C--;continue}}else{(B=r[C].match("a=ssrc:"+q[0]+" cname:(.+)"))&&(z=B[1]);(B=r[C].match("a=ssrc:"+q[0]+" msid:(.+)"))&&(G=B[1]);(B=r[C].match("a=ssrc:"+q[0]+" mslabel:(.+)"))&&(A=B[1]);(B=r[C].match("a=ssrc:"+q[0]+" label:(.+)"))&&(H=B[1]);if(0===r[C].indexOf("a=ssrc:"+t[0])){r.splice(C,1);C--;continue}if(0===r[C].indexOf("a=ssrc:"+q[0])){r.splice(C,1);C--;continue}}0===r[C].length&&(r.splice(C,1),C--)}if(0>q[0])return k;0>E&&(E=r.length);q[1]=Math.floor(4294967295*Math.random());
q[2]=Math.floor(4294967295*Math.random());t[1]=Math.floor(4294967295*Math.random());t[2]=Math.floor(4294967295*Math.random());for(C=0;C<q.length;C++)z&&(r.splice(E,0,"a=ssrc:"+q[C]+" cname:"+z),E++),G&&(r.splice(E,0,"a=ssrc:"+q[C]+" msid:"+G),E++),A&&(r.splice(E,0,"a=ssrc:"+q[C]+" mslabel:"+A),E++),H&&(r.splice(E,0,"a=ssrc:"+q[C]+" label:"+H),E++),z&&(r.splice(E,0,"a=ssrc:"+t[C]+" cname:"+z),E++),G&&(r.splice(E,0,"a=ssrc:"+t[C]+" msid:"+G),E++),A&&(r.splice(E,0,"a=ssrc:"+t[C]+" mslabel:"+A),E++),
H&&(r.splice(E,0,"a=ssrc:"+t[C]+" label:"+H),E++);r.splice(E,0,"a=ssrc-group:FID "+q[2]+" "+t[2]);r.splice(E,0,"a=ssrc-group:FID "+q[1]+" "+t[1]);r.splice(E,0,"a=ssrc-group:FID "+q[0]+" "+t[0]);r.splice(E,0,"a=ssrc-group:SIM "+q[0]+" "+q[1]+" "+q[2]);k=r.join("\r\n");k.endsWith("\r\n")||(k+="\r\n");return k}function l(k){return k?!1===k.audio?!1:void 0===k.audio.send||null===k.audio.send?!0:!0===k.audio.send:!0}function m(k){return k?!1===k.audio?!1:void 0===k.audio.I||null===k.audio.I?!0:!0===k.audio.I:
!0}function v(k){return k?!1===k.video?!1:void 0===k.video.send||null===k.video.send?!0:!0===k.video.send:!0}function w(k){return k?!1===k.video?!1:void 0===k.video.I||null===k.video.I?!0:!0===k.video.I:!0}$Soa(d);if(!$Sq)return{};if(!window.RTCPeerConnection)return d.L(this,"mesibo calls are not supported by this browser"),{};var x=a.iceServers||[{urls:"stun:stun.l.google.com:19302"}],D=a.iceTransportPolicy,F=a.bundlePolicy,y=!0===a.Ae;this.rb=!0;this.h=d;this.options=a;this.Ha=null;void 0!==a.rb&&
null!==a.rb&&(this.rb=!0===a.rb);this.U={jb:!1,f:null,Va:!1,ia:null,ya:null,Ic:null,c:null,P:{},Fd:null,mb:!0,wb:!1,volume:{value:null,J:null},bitrate:{value:null,zd:null,yd:null,pe:null,oe:null,J:null}};this.send=function(){this.Ne()};this.dtmf=function(){this.Me()};this.fe=function(k){this.setRemoteDescription(k)};this.S=function(){this.rc()};var M=this;this.Oa=function(k){var r=this.U;r.c&&r.ac?k&&!0!==k.completed?r.c.addIceCandidate(k):r.c.addIceCandidate(null):(r.X||(r.X=[]),r.X.push(k))};this.la=
function(){return this.eb};this.Pd=function(){if(this.U.c.getSenders()&&this.U.c.getSenders().length)for(var k=$Sa(this.U.c.getSenders()),r=k.next();!r.done;r=k.next())if((r=r.value)&&r.track&&"video"===r.track.kind)return r;return null};this.createOffer=function(k,r){this.eb=r;this.Yc(k,null)};this.createAnswer=function(k,r,n){this.eb=n;this.Yc(k,r)};this.close=function(){this.rc()};this.ra=function(k,r,n){if(void 0!=n&&null!=n){var q={};q.source=r.video.source;q.F=r.video.F;q.video=r.video.send;
q.audio=r.audio.send;this.h.Eb(this,q)}var t=this.U,z=this;q=!1;if(t.f&&r.update&&!t.Va){if((!r.update&&l(r)||r.update&&(r.audio.add||r.audio.replace))&&n.getAudioTracks()&&n.getAudioTracks().length)if(t.f.addTrack(n.getAudioTracks()[0]),$Su){var G=null,A=t.c.getTransceivers();if(A&&0<A.length){var H=$Sa(A);for(A=H.next();!A.done;A=H.next())if(A=A.value,A.sender&&A.sender.track&&"audio"===A.sender.track.kind||A.receiver&&A.receiver.track&&"audio"===A.receiver.track.kind){G=A;break}}G&&G.sender?G.sender.replaceTrack(n.getAudioTracks()[0]):
t.c.addTrack(n.getAudioTracks()[0],n)}else t.c.addTrack(n.getAudioTracks()[0],n);if((!r.update&&v(r)||r.update&&(r.video.add||r.video.replace))&&n.getVideoTracks()&&n.getVideoTracks().length){if(this.Ha){try{t.f.removeTrack(this.Ha),this.Ha.stop()}catch(B){}this.Ha=null}t.f.addTrack(n.getVideoTracks()[0]);if($Su){G=null;if((A=t.c.getTransceivers())&&0<A.length)for(H=$Sa(A),A=H.next();!A.done;A=H.next())if(A=A.value,A.sender&&A.sender.track&&"video"===A.sender.track.kind||A.receiver&&A.receiver.track&&
"video"===A.receiver.track.kind){G=A;break}G&&G.sender?G.sender.replaceTrack(n.getVideoTracks()[0]):t.c.addTrack(n.getVideoTracks()[0],n)}else t.c.addTrack(n.getVideoTracks()[0],n)}}else t.f=n,q=!0;if(!t.c){G={iceServers:x,iceTransportPolicy:D,bundlePolicy:F};"chrome"===$Sr.browserDetails.browser&&(G.sdpSemantics=72>$Sr.browserDetails.version?"plan-b":"unified-plan");A={optional:[{DtlsSrtpKeyAgreement:!0}]};y&&A.optional.push({googIPv6:!0});if(d.dc&&"object"===typeof d.dc)for(var E in d.dc)A.optional.push(d.dc[E]);
"edge"===$Sr.browserDetails.browser&&(G.bundlePolicy="max-bundle");t.c=new RTCPeerConnection(G,A);t.c.getStats&&(t.volume={},t.bitrate.value="0 kbits/sec");t.c.oniceconnectionstatechange=function(){t.c&&z.h.Db(z,t.c.iceConnectionState)};t.c.onicecandidate=function(B){!B.candidate||"edge"===$Sr.browserDetails.browser&&0<B.candidate.candidate.indexOf("endOfCandidates")?(t.wb=!0,!0===t.mb?z.cd(null):z.ce()):(B={candidate:B.candidate.candidate,sdpMid:B.candidate.sdpMid,sdpMLineIndex:B.candidate.sdpMLineIndex},
!0===t.mb&&z.cd(B))};t.c.ontrack=function(B){B.streams&&(t.ia=B.streams[0],t.ia.getTracks(),z.h.Aa(z,t.ia,!0,!0),B.track.onended||(B.track.onended=function(K){t.ia&&(t.ia.removeTrack(K.target),z.h.Aa(z,t.ia,!1,!1))},B.track.onmute=function(){t.ia&&z.h.Aa(z,t.ia,!1,!1)},B.track.onunmute=function(){try{z.h.Aa(z,t.ia,!1,!0)}catch(K){}}))}}if(q&&n){var C=!0===r.je;n.getTracks().forEach(function(B){if(C)if("audio"===B.kind)t.c.addTrack(B,n);else{var K=e(r.ld);t.c.addTransceiver(B,{direction:"sendrecv",
streams:[n],sendEncodings:[{rid:"f",active:!0,maxBitrate:K.high},{rid:"h",active:!0,maxBitrate:K.Na,scaleResolutionDownBy:2},{rid:"q",active:!0,maxBitrate:K.low,scaleResolutionDownBy:4}]})}else t.c.addTrack(B,n)})}("edge"===$Sr.browserDetails.browser||void 0===r||null===r?0:!0===r.data)&&!t.P[$Sv.b]&&(f($Sv.b,!1),t.c.ondatachannel=function(B){f(B.channel.label,B.channel)});if(t.f&&(z.h.cb(z,t.f,!0),E=t.f.getTracks()))for(E=$Sa(E),q=E.next();!q.done;q=E.next())if((q=q.value)&&"video"===q.kind){q.onended=
function(){z.h.cb(z,t.f,!1)};break}k?t.c.setRemoteDescription(k).then(function(){t.ac=k.sdp;if(t.X&&0<t.X.length){for(var B=0;B<t.X.length;B++){var K=t.X[B];K&&!0!==K.completed?t.c.addIceCandidate(K):t.c.addIceCandidate(null)}t.X=[]}z.Cd(r)},function(){z.h.Pa()}):this.Dd(r)};this.xb=function(k){return 2==k?!0:!1};this.sc=function(k){if(!k||!v(k))return!1;var r=this.xb(k.video.source);k.video.F||(k.video.source&&!r?k.video.F=k.video.source:k.video.F=2);var n=k.video.F;if(8===n){var q=120;n=160}else 1==
n?(q=240,n=320):9==n?(q=180,n=320):3==n?(q=720,n=1280):4==n?(q=1080,n=1920):5==n?(q=2160,n=3840):2==n?(q=480,n=640):10==n?(q=360,n=640):(q=480,n=640,k.video.F=2);r&&1920>n&&(q=1080,n=1920);k.video.width&&0<k.video.width&&(r=n/q,n=k.video.width,k.video.height||(q=n/r));k.video.height&&0<k.video.height&&(q=k.video.height);r={height:{ideal:q},width:{ideal:n}};q=this.xb(k.video.source)?10:0;k.video.rate&&0<k.video.rate&&(q=k.video.rate);q&&(n={},n.ideal=q,k.video.Hc&&0<k.video.Hc&&(q=k.video.Hc),n.max=
q,r.frameRate=n);return r};this.Yc=function(k,r){var n=this;k="object"===typeof k&&k?k:{audio:{send:!0,I:!0},video:{send:!0,I:!0}};k.video="object"===typeof k.video&&k.video?k.video:{send:!0,I:!0};k.audio="object"===typeof k.audio&&k.audio?k.audio:{send:!0,I:!0};var q=this.U;if(q.c){k.update=!0;if(!n.h.stream){if(k.audio.add){if(k.audio.s=!1,k.audio.replace=!1,k.audio.remove=!1,k.audio.send=!0,q.f&&q.f.getAudioTracks()&&q.f.getAudioTracks().length){n.h.L(n,"Can't add audio stream, there already is one");
return}}else k.audio.remove?(k.audio.s=!1,k.audio.replace=!1,k.audio.add=!1,k.audio.send=!1):k.audio.replace&&(k.audio.s=!1,k.audio.add=!1,k.audio.remove=!1,k.audio.send=!0);q.f?q.f.getAudioTracks()&&0!==q.f.getAudioTracks().length?!l(k)||k.audio.remove||k.audio.replace||(k.audio.s=!0):(k.audio.replace&&(k.audio.s=!1,k.audio.replace=!1,k.audio.add=!0,k.audio.send=!0),l(k)&&(k.audio.s=!1,k.audio.add=!0)):(k.audio.replace&&(k.audio.s=!1,k.audio.replace=!1,k.audio.add=!0,k.audio.send=!0),l(k)&&(k.audio.s=
!1,k.audio.add=!0));if(k.video.add){if(k.video.s=!1,k.video.replace=!1,k.video.remove=!1,k.video.send=!0,q.f&&q.f.getVideoTracks()&&q.f.getVideoTracks().length){n.h.L(n,"Can't add video stream, there already is one");return}}else k.video.remove?(k.video.s=!1,k.video.replace=!1,k.video.add=!1,k.video.send=!1):k.video.replace&&(k.video.s=!1,k.video.add=!1,k.video.remove=!1,k.video.send=!0);q.f?q.f.getVideoTracks()&&0!==q.f.getVideoTracks().length?!v(k)||k.video.remove||k.video.replace||(k.video.s=!0):
(k.video.replace&&(k.video.s=!1,k.video.replace=!1,k.video.add=!0,k.video.send=!0),v(k)&&(k.video.s=!1,k.video.add=!0)):(k.video.replace&&(k.video.s=!1,k.video.replace=!1,k.video.add=!0,k.video.send=!0),v(k)&&(k.video.s=!1,k.video.add=!0));k.re&&(k.data=!0)}if(l(k)&&k.audio.s&&v(k)&&k.video.s){n.h.M(n,!1);n.ra(r,k,q.f);return}}else k.update=!1,k.audio.s=!1,k.video.s=!1;if(k.update&&!q.Va){if(k.audio.remove||k.audio.replace){if(q.f&&q.f.getAudioTracks()&&q.f.getAudioTracks().length){var t=q.f.getAudioTracks()[0];
q.f.removeTrack(t);try{t.stop()}catch(I){}}if(q.c.getSenders()&&q.c.getSenders().length&&(t=!0,k.audio.replace&&$Su&&(t=!1),t)){t=$Sa(q.c.getSenders());for(var z=t.next();!z.done;z=t.next())(z=z.value)&&z.track&&"audio"===z.track.kind&&q.c.removeTrack(z)}}if(k.video.remove||k.video.replace){if(q.f&&q.f.getVideoTracks()&&q.f.getVideoTracks().length)if(t=q.f.getVideoTracks()[0],!k.video.remove&&$Sla)this.Ha=t;else{q.f.removeTrack(t);try{t.stop()}catch(I){}}if(q.c.getSenders()&&q.c.getSenders().length&&
(!k.video.replace||!$Su))for(t=$Sa(q.c.getSenders()),z=t.next();!z.done;z=t.next())(z=z.value)&&z.track&&"video"===z.track.kind&&q.c.removeTrack(z)}}if(k.stream){var G=k.stream;if(k.update&&q.f&&q.f!==d.stream&&!q.Va){try{for(var A=q.f.getTracks(),H=$Sa(A),E=H.next();!E.done;E=H.next()){var C=E.value;C&&C.stop()}}catch(I){}q.f=null}q.Va=!0;n.h.M(n,!1);n.ra(r,k,G)}else if(l(k)||v(k))if(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia){A={mandatory:{},optional:[]};k.update||this.xb(k.video.source)||
n.h.M(n,!0);var B=l(k);B&&k&&"object"===typeof k.audio&&(B=k.audio);var K=v(k);if(K&&k){q=!0===k.je;!0!==k.ib&&!q||r||k.video.source||(k.video.source=1);if(this.xb(k.video.source)){q=function(I,J,N){navigator.mediaDevices.getUserMedia(I).then(function(L){N?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(function(P){L.addTrack(P.getAudioTracks()[0]);J(null,L)}):J(null,L)}).catch(function(L){this.Ha=null;n.h.M(n,!1);J(L)})};var Q=function(I,J){n.h.M(n,!1);I?n.h.L(n,I):n.ra(r,k,J)};if(navigator.mediaDevices&&
navigator.mediaDevices.getDisplayMedia){A.video=this.sc(k);A.audio=k.te;navigator.mediaDevices.getDisplayMedia(A).then(function(I){n.h.M(n,!1);l(k)&&!k.audio.s?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(function(J){I.addTrack(J.getAudioTracks()[0]);n.ra(r,k,I)}):n.ra(r,k,I)},function(I){n.h.M(n,!1);d.L(n,I)});return}"chrome"===$Sr.browserDetails.browser?(A=$Sr.browserDetails.version,H=33,window.navigator.userAgent.match("Linux")&&(H=35),26<=A&&A<=H&&(A={video:{mandatory:{we:!0,
maxWidth:window.screen.width,maxHeight:window.screen.height,Ee:k.$d,maxFrameRate:k.$d,chromeMediaSource:"screen"}},audio:l(k)&&!k.audio.s},q(A,Q))):"firefox"===$Sr.browserDetails.browser&&(33<=$Sr.browserDetails.version?(A={video:{Ge:k.video.source,mediaSource:k.video.source},audio:l(k)&&!k.audio.s},q(A,function(I,J){Q(I,J);if(!I)var N=J.currentTime,L=window.setInterval(function(){J||window.clearInterval(L);if(J.currentTime==N&&(window.clearInterval(L),J.onended))J.onended();N=J.currentTime},500)})):
(q=Error("NavigatorUserMediaError"),q.name="Your version of Firefox does not support screen sharing, please install Firefox 33 (or more recent versions)",n.h.M(n,!1),d.L(n,q)));return}K=this.sc(k)}(!k||!K&&B||2!==k.video.source)&&navigator.mediaDevices.enumerateDevices().then(function(I){var J=I.some(function(O){return"audioinput"===O.kind});I=(2==k.video.source?!0:!1)||I.some(function(O){return"videoinput"===O.kind});var N=l(k),L=v(k),P=k&&!1!==k.audio&&!1!==k.audio.send&&void 0!==k.xc&&null!==k.xc?
!0===k.xc:!1,R=k&&!1!==k.video&&!1!==k.video.send&&void 0!==k.yc&&null!==k.yc?!0===k.yc:!1;if(N||L||P||R)if(N=N?J:!1,L=L?I:!1,N||L){if(!N&&P)return n.h.M(n,!1),d.L(n,"Audio capture is required, but no capture device found"),!1;if(!L&&R)return n.h.M(n,!1),d.L(n,"Video capture is required, but no capture device found"),!1}else return n.h.M(n,!1),d.L(n,"No capture device found"),!1;J={audio:J&&!k.audio.s?B:!1,video:I&&!k.video.s?K:!1};J.audio||J.video?navigator.mediaDevices.getUserMedia(J).then(function(O){n.h.M(n,
!1);n.ra(r,k,O)}).catch(function(O){n.h.M(n,!1);n.h.L(n,{code:O.code,name:O.name,message:O.message})}):(n.h.M(n,!1),n.ra(r,k,G))}).catch(function(I){this.Ha=null;n.h.M(n,!1);d.L(n,"enumerateDevices error",I)})}else d.L(n,"getUserMedia not available");else n.ra(r,k)};this.setRemoteDescription=function(k){var r=this,n=this.U;k?n.c?n.c.setRemoteDescription(k).then(function(){n.ac=k.sdp;if(n.X&&0<n.X.length){for(var q=0;q<n.X.length;q++){var t=n.X[q];t&&!0!==t.completed?n.c.addIceCandidate(t):n.c.addIceCandidate(null)}n.X=
[]}},function(){r.h.Pa()}):r.h.L(r,"no PeerConnection: first create pc"):r.h.L(r,"invalid jsep")};this.jd=function(k,r,n,q){if(q){var t=null;k||r||!n?k&&r?t="sendrecv":k&&!r?t="sendonly":!k&&r&&(t="recvonly"):t="inactive";if(t)try{q.setDirection?q.setDirection(t):q.direction=t}catch(z){}}};this.kd=function(k){var r=null,n=null,q=this.U.c.getTransceivers();if(q&&0<q.length){q=$Sa(q);for(var t=q.next();!t.done;t=q.next())if(t=t.value,t.sender&&t.sender.track&&"audio"===t.sender.track.kind||t.receiver&&
t.receiver.track&&"audio"===t.receiver.track.kind)r||(r=t);else if(t.sender&&t.sender.track&&"video"===t.sender.track.kind||t.receiver&&t.receiver.track&&"video"===t.receiver.track.kind)n||(n=t)}q=l(k);t=m(k);this.jd(q,t,k.audio.remove,r);r=v(k);q=w(k);this.jd(r,q,k.video.remove,n)};this.Dd=function(k){var r=this,n=this.U,q=!0===k.ib,t={};$Su?this.kd(k):(t.offerToReceiveAudio=m(k),t.offerToReceiveVideo=w(k));!0===k.ye&&(t.iceRestart=!0);var z=v(k);if(z&&q&&"firefox"===$Sr.browserDetails.browser){var G=
n.c.getSenders().find(function(H){return"video"===H.track.kind});if(G){var A=G.getParameters();A||(A={});k=e(k.ld);A.encodings=[{rid:"f",active:!0,maxBitrate:k.high},{rid:"h",active:!0,maxBitrate:k.Na,scaleResolutionDownBy:2},{rid:"q",active:!0,maxBitrate:k.low,scaleResolutionDownBy:4}];G.setParameters(A)}}n.c.createOffer(t).then(function(H){H.sdp=H.sdp;z&&q&&("chrome"===$Sr.browserDetails.browser||"safari"===$Sr.browserDetails.browser)&&(H.sdp=h(H.sdp));n.ya=H.sdp;n.c.setLocalDescription(H).catch(function(){r.h.Pa()});
n.Ic=t;(n.wb||n.mb)&&r.h.Qa(r,H)},function(){r.h.Pa()})};this.Cd=function(k){var r=this.U,n=!0===k.ib,q=null;$Su?this.kd(k):"firefox"===$Sr.browserDetails.browser||"edge"===$Sr.browserDetails.browser?q={offerToReceiveAudio:m(k),offerToReceiveVideo:w(k)}:q={mandatory:{OfferToReceiveAudio:m(k),OfferToReceiveVideo:w(k)}};v(k)&&n&&"firefox"===$Sr.browserDetails.browser&&(n=r.c.getSenders()[1],n.getParameters(),k=e(k.ld),n.setParameters({encodings:[{rid:"high",active:!0,priority:"high",maxBitrate:k.high},
{rid:"medium",active:!0,priority:"medium",maxBitrate:k.Na},{rid:"low",active:!0,priority:"low",maxBitrate:k.low}]}));var t=this;r.c.createAnswer(q).then(function(z){var G={type:z.type,sdp:z.sdp};z.sdp=G.sdp;r.ya=z.sdp;r.c.setLocalDescription(z).catch(function(){t.h.Pa()});r.Ic=q;(r.wb||r.mb)&&t.h.Qa(t,G)},function(){t.h.Pa()})};this.cd=function(k){M.h.Oa(this,k)};this.ce=function(){var k=this.U;k.ya&&(k.ya={type:k.c.localDescription.type,sdp:k.c.localDescription.sdp},!1===k.mb&&(k.ya.trickle=!1),
k.Le=!0,M.h.Qa(this,k.ya))};this.sa=function(k,r){var n=this.U;if(!n.c||!n.f)return!1;if(k){if(!n.f.getVideoTracks()||0===n.f.getVideoTracks().length)return!1;n.f.getVideoTracks()[0].enabled=!r}else{if(!n.f.getAudioTracks()||0===n.f.getAudioTracks().length)return!1;n.f.getAudioTracks()[0].enabled=!r}return!0};this.rc=function(){var k=this.U;if(k){if(k){k.ia=null;k.volume&&(k.volume.local&&k.volume.local.J&&clearInterval(k.volume.local.J),k.volume.remote&&k.volume.remote.J&&clearInterval(k.volume.remote.J));
k.volume={};k.bitrate.J&&clearInterval(k.bitrate.J);k.bitrate.J=null;k.bitrate.zd=null;k.bitrate.yd=null;k.bitrate.pe=null;k.bitrate.oe=null;k.bitrate.value=null;try{if(!k.Va&&k.f)for(var r=k.f.getTracks(),n=$Sa(r),q=n.next();!q.done;q=n.next()){var t=q.value;t&&t.stop()}}catch(z){}k.Va=!1;k.f=null;try{k.c.close()}catch(z){}k.c=null;k.X=null;k.ya=null;k.ac=null;k.wb=!1;k.P={};k.Fd=null}this.h.Cb(this)}}}var $Sq,$Sla,$Sr,$Sma,$Sna,$Ss,$St,$Su;
function $Sw(a,d){if(void 0===d||"undefined"===typeof d)d=1;if(null==a||"object"!=typeof a)return a;if(a instanceof Date){var e=new Date;e.setTime(a.getTime());return e}if(0==d)return null;if(a instanceof Array){e=[];for(var f=0,h=a.length;f<h;f++)e[f]=$Sw(a[f],d-1);return e}if(a instanceof Object){e={};for(f in a)a.hasOwnProperty(f)&&(e[f]=$Sw(a[f],d-1));return e}throw Error("Unable to copy obj! type not supported.");}function $Sx(a,d){return d in a&&"function"===typeof a[d]?!0:!1}
function $Sy(){return parseInt(Date.now())}function $Sz(){return parseInt($Sy()/1E3)}function $SA(a,d,e){d+=e;return d>a?d-a:0}function $SB(a){return a&&void 0!==a&&"undefined"!==typeof a&&""!=a?!1:!0}var $Spa="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");function $SC(a){return 10>a?"0"+a:""+a}
function $SD(a,d){var e=new Date,f=e.getTime()-1E3*(3600*e.getHours()+60*e.getMinutes()+e.getSeconds());if(void 0===a||"undefined"===typeof a)a=0;0<a&&e.setTime(a);var h=$Spa[e.getMonth()]+" "+$SC(e.getDate())+", "+e.getFullYear(),l=e.getHours();e=e.getMinutes();var m="";d&&(m=" AM",12<=l&&(m=" PM",12<l&&(l-=12)));d=$SC(l)+":"+$SC(e)+m;a>=f?h="Today":864E5>=f-a&&(h="Yesterday");return{tc:h,time:d}}function $SE(a){if($SB(a))return 0;a=parseInt(a,10);return isNaN(a)?0:a}
function $Sqa(a){window.addEventListener(0<=["iPad","iPhone","iPod"].indexOf(navigator.platform)?"pagehide":"beforeunload",a)}function $Sra(){this.J=-1;this.j=null;this.host="";this.port=0;this.url="";this.$=null;this.stopped=this.closed=this.l=0;this.b=10;this.g=30;this.delay=this.b;this.D=0}function $SF(a){if(NaN==this.Ga||void 0==this.Ga)this.Ga={};return this.Ga[a]}function $Ssa(a){if(NaN==this.Ga||void 0==this.Ga)this.Ga={};this.Ga[a.j]=a}$S=$Sra.prototype;
$S.start=function(){this.stopped=0;this.delay=this.b;$SG(this)};$S.stop=function(){$SH(this);this.stopped=1;this.disconnect()};$S.hc=function(a,d,e){this.host=d;this.port=e;this.url=(a?"wss":"ws")+"://"+d+":"+e};function $Sta(a,d){$SH(a);a.J=setTimeout(function(){$SG(a)},d)}function $SH(a){-1!=a.J&&clearInterval(a.J);a.J=-1}$S.send=function(a){this.j.send(a)};$S.Ub=function(a){null!=this.$&&this.$.Ub(a)};$S.Bb=function(){this.l=1;$SH(this);this.delay=this.b;null!=this.$&&this.$.Bb()};
$S.Ab=function(){if(!this.closed){$SH(this);this.closed=1;this.j=null;var a=1;null!=this.$&&(a=this.$.Ab());a&&!this.stopped&&(a=1E3*(5+this.delay*Math.random()),this.delay+=5,this.delay>this.g&&(this.delay=this.g),$Sta(this,a))}};$S.Tb=function(){null!=this.$&&this.$.Tb();this.Ab()};
function $SG(a){if(!a.stopped)if($SH(a),1===(null!=a.j?a.j.readyState:0))a.j.onopen=function(){$SF(this).Bb()};else try{a.closed=0,a.l=0,null!=a.$&&$Sua(a.$),a.j=new WebSocket(a.url),$Ssa(a),a.j.binaryType="arraybuffer",a.j.onopen=function(){$SF(this).Bb()},a.j.onmessage=function(d){$SF(this).Ub(d)},a.j.onclose=function(){$SF(this).Ab()},a.j.onerror=function(){$SF(this).Tb()}}catch(d){}}
$S.disconnect=function(){$SH(this);null!=this.j&&(this.j.onclose=function(){},this.j.onerror=function(){},this.j.close(1E3),this.j=null)};function $SI(a,d,e){for(var f=[],h=Math.max(a.length,d.length),l=0,m=0;m<h||l;)l=l+(m<a.length?a[m]:0)+(m<d.length?d[m]:0),f.push(l%e),l=Math.floor(l/e),m++;return f}function $Sva(a,d,e){if(0>a)return null;if(0==a)return[];for(var f=[];;){a&1&&(f=$SI(f,d,e));a>>=1;if(0===a)break;d=$SI(d,d,e)}return f}
function $Swa(a,d,e){if(null===a)return null;for(var f=[],h=[1],l=0;l<a.length;l++)a[l]&&(f=$SI(f,$Sva(a[l],h,e),e)),h=$Sva(d,h,e);if(16==e){e=f;l=0;a=[];for(f=0;f<e.length;f++)f&1?(a[l]|=e[f]<<4,l++):a[l]=e[f];return a}a="";for(l=f.length-1;0<=l;l--)a+=f[l].toString(e);return a}
ArrayBuffer.b||(ArrayBuffer.b=function(a,d){if(!(a instanceof ArrayBuffer))throw new TypeError("Source must be an instance of ArrayBuffer");if(d<=a.byteLength)return a.slice(0,d);a=new Uint8Array(a);d=new Uint8Array(new ArrayBuffer(d));d.set(a);return d.buffer});function $SJ(a,d){var e=0;for(--d;0<=d;d--)e=256*e+a[0+d];return e}function $Sxa(a,d){for(var e=0,f=0;4>f;f++)d[e++]=a&255,a>>>=8}function $Sya(a,d,e,f){for(var h=0;h<d;h++)e[f++]=a[h+0]&255}
function $Sza(a,d,e,f){for(var h=0;h<d;h++)e[f++]=a.charCodeAt(h+0)}function $SK(a,d,e){for(var f="",h=d;h<d+e;h++){var l=parseInt(a[h],10);if(0==l)break;f+=String.fromCharCode(l)}return f}function $SAa(a){return 65<=a&&70>=a?10+(a-65):97<=a&&103>=a?10+(a-97):48<=a&&57>=a?a-48:-1}function $SL(){this.data=[]}$SL.prototype.add=function(a){this.data.push(a)};$SL.prototype.remove=function(){this.data.pop()};$SL.prototype.first=function(){return 0==this.data.length?null:this.data.shift()};
$SL.prototype.size=function(){return this.data.length};function $SM(a){this.mode=0==a?0:1;this.reset()}$SM.prototype.reset=function(){this.failed=this.g=this.start=this.b=this.G=0;this.id=this.result=this.H=-1;this.ab=this.Ka=0;this.items=this.address=null;this.buffer=new Uint8Array(32);0==this.mode&&(this.G=8)};function $SBa(a,d){a.id=d;d=4;a.buffer[d++]=a.id&255;a.buffer[d++]=a.id>>8&255;a.buffer[d++]=a.id>>16&255;a.buffer[d++]=a.id>>24&255}$SM.prototype.tb=function(){return this.id};
$SM.prototype.Nb=function(){return this.address};function $SCa(a){var d=0;a.H=a.buffer[d++];a.result=a.buffer[d++];d++;d++;a.id=a.buffer[d]+256*a.buffer[d+1]+65536*a.buffer[d+2]+16777216*a.buffer[d+3];a.b=d+4}
function $SDa(a,d){void 0==d&&console.log("len undefined");var e=d+a.G;if(!(a.buffer.byteLength>e)){if(0<a.b&&(a.buffer.copyWithin(0,a.b,a.G-a.b),a.G-=a.b,a.b=0,e=d+a.G,a.buffer.byteLength>e))return;d=e-a.buffer.byteLength;64>d&&(d=64);d=new Uint8Array(a.buffer.byteLength+d);d.set(a.buffer);a.buffer=d}}function $SN(a,d,e){0==e&&(e=d.length);$SDa(a,e);a.buffer.set(new Uint8Array(d),a.G);a.G+=e}function $SO(a){return a.buffer.slice(8,a.G)}
function $SP(a,d){0==d&&0==a.b&&$SCa(a);a.g=0;a.items=[];for(a.map={};$SEa(a)&&0==a.g&&0==a.failed;);return a.failed||1!=a.mode||0==a.g?null:a.items}
function $SQ(a,d,e,f,h){if(!(0!=a.mode||2047<d)){$SDa(a,f+8);2==d&&(a.g=1);0<h&&e&&0<f&&(f=256>e?1:65536>e?2:16777216>e?3:4294967296>e?4:1099511627776>e?5:281474976710656>e?6:72057594037927936>e?7:8);var l=0;16777215<f?l=4:65535<f?l=3:255<f?l=2:0<f&&(l=1);var m=1,v=d&31,w=0;31<d||2<l?(m=2,v|=224):5>f?(l=0,w=f):w=l+4;a.buffer[a.G++]=v|w<<5;1<m&&(a.buffer[a.G++]=d>>5|l-1<<6);l&&$SFa(a,f,l);if(h)$SFa(a,e,f);else for(d=f,f=0;f<d;f++)a.buffer[a.G++]=e[f+0]&255}}
function $SFa(a,d,e){for(var f=0;f<e;f++)a.buffer[a.G++]=d&255,d/=256}function $SGa(a,d,e){for(var f=0;e--;)f*=256,f+=a.buffer[d+e]&255;return f}function $SR(a,d,e,f){6==d?a.Ka=e:3==d&&(a.ab=e);$SQ(a,d,e,f,1)}function $SS(a,d,e){void 0!=e&&null!=e&&(e=parseInt(e),0!=e&&$SR(a,d,e,1))}
function $ST(a,d,e,f){4==d&&(a.address=e);if("[object String]"===Object.prototype.toString.call(e)){for(var h=e.length,l=new Uint8Array(h),m=0;m<h;m++)l[m]=e.charCodeAt(m);e=l}else e=Uint8Array.from(e);if(0==f||void 0==f)f=e.byteLength;$SQ(a,d,e,f,0)}function $SU(a,d,e){for(var f=e.length,h=new Uint8Array(f+1),l=0;l<f;l++)h[l]=e.charCodeAt(l);h[f]=0;e=h;$SQ(a,d,e,e.byteLength,0)}
function $SEa(a){var d={},e=a.buffer[a.b],f=e>>5,h=0;e&=31;var l=f,m=1;if(1==e&&0<a.items.length)return a.g=1,!0;5==f||6==f?h=f-4:7==f&&(f=a.buffer[a.b+1],h=(f>>6)+1,e|=(f&63)<<5,m=2);if(a.G<a.b+m+h)return!1;d.type=e;h&&(l=$SGa(a,a.b+m,h));if(a.G<a.b+m+h+l)return!1;d.len=l;d.val=0;f=m+h+a.b;d.data=a.buffer.slice(f,f+l);4>=l&&(d.val=$SGa(a,a.b+m+h,l));a.items.push(d);a.map[e]=d;a.b+=m+h+l;a.b==a.G&&(a.g=1,a.G=0,a.b=0);return!0}
window.indexedDB=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB;window.IDBTransaction=window.IDBTransaction||window.webkitIDBTransaction||window.g||{READ_WRITE:"readwrite"};window.IDBKeyRange=window.IDBKeyRange||window.webkitIDBKeyRange||window.b;function $SHa(){if(!("indexedDB"in window))return!1;$SIa(this)}function $SIa(a){$Sn(function(d){a.db=null;a.ready=!1;d.b=0})}
function $SJa(a,d,e){var f,h;$Sn(function(l){a.ue=d;f=a;h=window.indexedDB.open(d,1);h.onerror=function(){e(null)};h.onsuccess=function(m){f.db=m.target.result;f.ready=!0;e(f.db)};h.onupgradeneeded=function(m){f.db=m.target.result;$SKa(f);$SLa(f)};l.b=0})}$SHa.prototype.open=function(a,d){var e=this,f,h;return $Sn(function(l){f=e;if("function"===typeof d)return $SJa(f,a,d),l.return();h=new Promise(function(m){$SJa(f,a,m)});return l.return(h)})};
function $SKa(a){a=a.db.createObjectStore("messages",{autoIncrement:!0});a.createIndex("peer",["peer","groupid"],{unique:!1});a.createIndex("ts","ts",{unique:!1});a.transaction.oncomplete=function(){}}function $SLa(a){a=a.db.createObjectStore("contacts",{keyPath:["address","groupid"]});a.createIndex("address","address",{unique:!1});a.createIndex("groupid","groupid",{unique:!1});a.createIndex("name","name",{unique:!1});a.createIndex("ts","ts",{unique:!1});a.transaction.oncomplete=function(){}}
function $SMa(a){return a.db.transaction(["messages"],"readwrite").objectStore("messages")}function $SNa(a){return a.db.transaction(["contacts"],"readwrite").objectStore("contacts")}function $SOa(a,d){a=$SNa(a);d=$Sw(d,2);d.groupid=$SE(d.groupid);delete d.status;d=a.put(d);d.onerror=function(){};d.onsuccess=function(){}}function $SPa(a,d){a=$SNa(a).index("name").getAll();a.onerror=function(){d([])};a.onsuccess=function(e){d(e.target.result)}}
function $SQa(a,d){var e,f,h;$Sn(function(l){if(1==l.b){e=a;if("function"===typeof d)return $SPa(e,d),l.return();f=new Promise(function(m){$SPa(e,m)});h=null;return $Si(l,f.then(function(){}),2)}return l.return(h)})}
$SHa.prototype.read=function(a,d,e,f,h){var l=$SMa(this);if(null==a||void 0==a)a="";if(null==d||void 0==d)d=0;if(0!=d||""!=a)return l=l.index("peer"),a=IDBKeyRange.only([a,d]),l.openCursor(a,"prev").onsuccess=function(m){if(m=m.target.result){if(e)try{var v=e;e=0;m.advance(v);return}catch(w){h(null);return}if(v=m.value)if(0<v.groupid&&v.hasOwnProperty("sender")&&(v.peer=v.sender,delete v.sender),h(v),f--,0==f)h(null);else try{m.continue()}catch(w){h(null)}else h(null)}else h(null)},!0};
function $SV(a,d,e,f,h){a=$SMa(a);if(null==e||void 0==e)e="";if(null==f||void 0==f)f=0;a=a.index("peer");e=IDBKeyRange.only([e,f]);var l=!1;a.openCursor(e,"prev").onsuccess=function(m){if(m=m.target.result){var v=m.value;if(v&&(!l||3!=h||2==v.status)){if(v.id==d||3==h&&l)if(l=!0,v.status=h,m.update(v).onsuccess=function(){},3!=h)return;try{m.continue()}catch(w){}}}}}function $SRa(a){var d=window.localStorage;this.name=a+"_";this.storage=d;this.ed=JSON}
$SRa.prototype={clear:function(){this.storage.clear();return this},getItem:function(a,d){a=this.storage.getItem(this.name+a);return null==a?"undefined"!=typeof d?d:null:this.ed.parse(a)},removeItem:function(a){this.storage.removeItem(this.name+a);return this},setItem:function(a,d){this.storage.setItem(this.name+a,this.ed.stringify(d));return this}};
function $SSa(a){if(a.qa&&!a.gb)if(a.ca)a.send(a.ca);else{var d=a.Tc.first();if(null!=d){a.Lc=[];var e=new $SM(0);d.id&&a.Lc.push(d.id);e.H=2;e.result=1;e.id=0;var f=parseInt(d.fid,10)&65535;$SR(e,17,f,2);$SR(e,1,0,0);f=parseInt(d.id,10);0<f&&$SR(e,3,f,4);f=parseInt(d.channel,10);0<f&&$SR(e,10,f,1);f=parseInt(d.type,10);0<f&&$SR(e,11,f,1);f=parseInt(d.flag,10);0<f&&$SR(e,9,f,4);d.hasOwnProperty("groupid")?(f=parseInt(d.groupid,10),0<f?$SR(e,6,f,4):$ST(e,4,d.peer,0)):$ST(e,4,d.peer,0);f=parseInt(d.expiry,
10);f!=a.Sb&&$SR(e,8,f,4);f=parseInt(d.refid,10);0<f&&$SR(e,13,f,4);d.data?$ST(e,7,d.data,0):$ST(e,7,d.message,0);a.ca=e;a.send(a.ca)}}}
$SW.prototype.V=function(a,d,e){var f=this.j;if(!f.j&&!f.stopped){var h=$Sz();5>h-f.D||(f.D=h,$SH(f),$SG(f))}if(!a.hasOwnProperty("peer")&&!a.hasOwnProperty("groupid"))return!1;a=$Sw(a);a.groupid=$SE(a.groupid);if(0<a.groupid||!a.hasOwnProperty("peer"))a.peer="";a.status=0;"[object String]"===Object.prototype.toString.call(e)?a.message=e:a.data=e;a.id=d;a.fid=this.Hd++;a.origin=0;a.hasOwnProperty("expiry")||(a.expiry=this.Sb);a.hasOwnProperty("channel")||(a.channel=0);a.hasOwnProperty("type")||(a.type=
0);a.hasOwnProperty("flag")||(a.flag=3);a.hasOwnProperty("refid")||(a.refid=0);this.Tc.add(a);$SSa(this);0<a.id&&(a.ts=$Sy(),$STa(this,a));return!0};
$SW.prototype.vd=function(a,d,e){if(!a.hasOwnProperty("peer")&&!a.hasOwnProperty("groupid"))return!1;a=$Sw(a);a.flag|=256;var f=new $SM(0);e.hasOwnProperty("filetype")&&($SR(f,16,e.filetype,2),a.filetype=e.filetype);e.hasOwnProperty("filesize")&&($SR(f,17,e.filesize,4),a.filesize=e.filesize);e.hasOwnProperty("fileflags")&&($SR(f,18,e.fileflags,4),a.fileflags=e.fileflags);e.hasOwnProperty("fileurl")&&($SU(f,19,e.fileurl),a.fileurl=e.fileurl);e.hasOwnProperty("title")&&($SU(f,1,e.title),a.title=e.title);
e.hasOwnProperty("message")&&($SU(f,2,e.message),a.message=e.message);e.hasOwnProperty("launchurl")&&($SU(f,3,e.launchurl),a.launchurl=e.launchurl);e.hasOwnProperty("tn")&&($ST(f,4,e.tn,0),a.tn=e.tn);e=$SO(f);return this.V(a,d,e)};$SW.prototype.wd=function(a,d){if(!a.hasOwnProperty("peer")&&!a.hasOwnProperty("groupid"))return!1;a=$Sw(a);a.flag=1048836;a.expiry=0;var e=new $SM(0);$SR(e,21,d,2);return this.V(a,0,$SO(e))};
$SW.prototype.bd=function(a,d){if(!a.hasOwnProperty("peer")&&!a.hasOwnProperty("groupid"))return!1;a=$Sw(a);a.channel=129;a.flag=256;a.expiry=2592E3;var e=new $SM(0);a:{"string"!=typeof d&&(d=d.toString());d=d.split("");for(var f=[],h=d.length-1;0<=h;h--){var l=parseInt(d[h],10);if(isNaN(l)){d=null;break a}f.push(l)}d=f}d=$Swa(d,10,16);$SQ(e,20,d,d.length,0);return this.V(a,this.random(),$SO(e))};
function $STa(a,d){d.date=$SD(d.ts);if(!(!d.id||d.channel||d.flag&516)){d.user=a.sb(d.peer,0);d.group=null;d.groupid&&(d.group=a.sb("",d.groupid));var e=d.group?d.group:d.user;if(!e.na||d.ts>=e.na.ts)if(e.na=d,0==d.origin){e.w=e.na.w;$SUa(a,e);for(var f=0,h=0;h<a.ea.length;h++)if(0<e.u&&a.ea[h].u==e.u||e.address==a.ea[h].address){0!=h&&(a.ea.splice(h,1)[0],a.ea.unshift(e));f=1;break}0==f&&a.ea.unshift(e)}for(var l in a.Fa)e=a.Fa[l],f=e,h=d,$SVa(f,h)?(18!=h.status||f.Ea&&1!=h.origin||self.ba&&!(h.w>
self.ba.w)||(self.ba=h),1==h.origin?f.R.unshift(h):(f.R.push(h),$SWa(f,h)),f=!0):f=!1,f&&e.Ea&&18==d.status&&(d.status=19);a.Kc[d.id]=d;a.db&&0==d.origin&&(a=a.db,0==d.id||0<d.channel||(d=$Sw(d,1),0<d.groupid&&(d.sender=d.peer,d.peer=""),delete d.fid,delete d.data,delete d.datalen,delete d.user,delete d.group,delete d.date,$SMa(a).add(d)))}}function $SXa(a){a.ca=null;setTimeout(function(){$SSa(a)},a.Ac)}function $SYa(a,d,e){a=a.substring(d,d+e);return parseInt(a,16)}
function $SZa(a,d){for(var e=d.length,f=new Uint8Array(16),h=0;32>h;h+=2)f[h>>1]=parseInt(d.substr(h,2),16);a.cookie=f;f=32+parseInt(d[11],16)/2;h=d.substring(f,e);var l=15-parseInt(h[0],16);a.uid=$SYa(h,1,l)^$SYa(h,1+l,l);f+=1+2*l;h=d.substring(f,e);l=15-parseInt(h[0],16);h=d.substring(f+(1+2*l),e);a.kc=parseInt(h,16);0!=a.uid&&0!=l&&0!=a.kc||console.log("Invalid token: "+d)}
function $S_a(a,d,e,f,h,l){var m=new Uint8Array(4+f.byteLength+h.byteLength+l.length);$Sxa(d,m);$Sya(h,h.byteLength,m,4);$Sya(f,f.byteLength,m,4+h.byteLength);$Sza(l,l.length,m,4+f.byteLength+h.byteLength);crypto.subtle.digest("SHA-256",m).then(function(v){v=new Uint8Array(v);var w=new $SM(0);w.H=1;w.result=1;w.id=e;$ST(w,11,v,v.byteLength);0<a.ha.length&&$ST(w,16,a.ha,a.ha.byteLength);a.send(w)})}function $S0a(a){0!=a.qa&&(a.ta&&$S1a(a),$S2a(a),a.yb=setTimeout(function(){$S1a(a)},a.Dc))}
function $S2a(a){-1!=a.yb&&clearInterval(a.yb);a.yb=-1}function $S1a(a){if(0!=a.qa){var d=new $SM(0),e=a.ta;d.H=16;d.result=0;d.id=e;a.ta=0;a.send(d)}}function $S3a(a){this.notify=a;this.Ob=this.flags=0;this.startTime=this.f=this.Ta=this.Za=this.c=null;this.videoWidth=this.videoHeight=0;this.Nc={offerToReceiveAudio:1,offerToReceiveVideo:1};this.configuration={iceServers:[{url:"stun:stun.l.google.com:19302"}]}}$S=$S3a.prototype;
$S.La=function(a,d){if(!d)return!1;a&&(this.Za=document.getElementById(a));return(this.Ta=document.getElementById(d))?!0:!1};$S.W=function(a){if(this.notify){var d=this.notify;d.a&&d.a&&(d.a.ua=$Sy(),d.a.Wb=2==a?1:0,16==a&&(d.a.C=null),16==a?$S4a(d,0,98,0):2==a?(d.a.Yd++,$SX(d,48)):3==a&&$SX(d,50))}};function $S5a(a,d){d=JSON.stringify(d);if(a.notify&&(a=a.notify,a.a&&a.a)){a.a.ua=$Sy();a.a.Ua|=1;var e=8;a.a.ec&&(e=5,a.a.ec=0);a.W(a.a.id,null,e,d,0)}}
function $S6a(a,d){return $Sn(function(e){if(1==e.b)return e.g=2,$Si(e,a.c.setLocalDescription(d),4);if(2!=e.b)return $S5a(a,d),$Sj(e,0);$Sk(e);e.b=0})}function $S7a(a){$Sn(function(d){return a.f?$Si(d,a.f.getTracks().forEach(function(e){return e.stop()}),0):d.return()})}
function $S8a(a,d){var e,f;return $Sn(function(h){switch(h.b){case 1:return a.Za&&a.Za.addEventListener("loadedmetadata",function(){}),a.Ta.addEventListener("loadedmetadata",function(){}),d&&a.Ta.addEventListener("resize",function(){a.startTime&&(window.performance.now(),a.startTime=null)}),h.g=2,$Si(h,navigator.mediaDevices.getUserMedia({audio:!0,video:!0}),4);case 4:return e=h.N,a.Za&&(a.Za.srcObject=e),a.f=e,h.return(!0);case 2:f=$Sk(h),alert("getUserMedia() error: "+f.name);case 3:return h.return(!1)}})}
function $S9a(a,d){return $Sn(function(e){if(a.c)return e.return();a.f||$S8a(a,d);a.startTime=window.performance.now();d&&a.f.getVideoTracks();a.f.getAudioTracks();a.c=new RTCPeerConnection(a.configuration);a.c.onicecandidate=function(f){if(f.candidate){var h={type:"candidate"};h.candidate=f.candidate.candidate;h.id=f.candidate.sdpMid;h.label=f.candidate.sdpMLineIndex;$S5a(a,h)}};a.c.oniceconnectionstatechange=function(){var f=a.c.iceConnectionState;"failed"===f||"closed"===f?a.S():"connected"===
f?a.W(2):"disconnected"===f&&a.W(3)};a.c.ontrack=function(f){a.Ta.srcObject!==f.streams[0]&&(a.Ta.srcObject=f.streams[0])};a.f.getTracks().forEach(function(f){return a.c.addTrack(f,a.f)});e.b=0})}$S.call=function(a){var d=this,e;return $Sn(function(f){switch(f.b){case 1:return $Si(f,$S9a(d,a),2);case 2:return f.g=3,d.Nc.offerToReceiveVideo=a?1:0,$Si(f,d.c.createOffer(d.Nc),5);case 5:return e=f.N,$Si(f,$S6a(d,e),6);case 6:$Sj(f,0);break;case 3:$Sk(f),f.b=0}})};
$S.answer=function(a,d,e){var f=this,h,l;return $Sn(function(m){switch(m.b){case 1:return $Si(m,$S9a(f,e),2);case 2:return h=JSON.parse(d),m.g=3,$Si(m,f.c.setRemoteDescription(h),5);case 5:$Sj(m,4);break;case 3:$Sk(m);case 4:return m.g=6,$Si(m,f.c.createAnswer(),8);case 8:return l=m.N,$Si(m,$S$a(f,l),9);case 9:$Sj(m,0);break;case 6:$Sk(m),m.b=0}})};$S.S=function(){this.c&&(this.c.close(),this.c=null);this.Ob=1;$S7a(this)};
function $S$a(a,d){return $Sn(function(e){if(1==e.b)return e.g=2,$Si(e,a.c.setLocalDescription(d),4);if(2!=e.b)return $S5a(a,d),$Sj(e,0);$Sk(e);e.b=0})}$S.sa=function(){};
function $Sab(a,d){var e,f,h;$Sn(function(l){switch(l.b){case 1:e=JSON.parse(d);if("candidate"==e.type)return h=new RTCIceCandidate({candidate:e.candidate,sdpMid:e.id}),l.g=12,$Si(l,a.c.addIceCandidate(h),14);if("answer"!=e.type){l.b=0;break}l.g=5;return $Si(l,a.c.setRemoteDescription(e),7);case 7:$Sj(l,6);break;case 5:$Sk(l);case 6:return l.g=8,$Si(l,a.c.createAnswer(),10);case 10:return f=l.N,$Si(l,$S$a(a,f),11);case 11:$Sj(l,0);break;case 8:$Sk(l);l.b=0;break;case 14:$Sj(l,0);break;case 12:$Sk(l),
l.b=0}})}function $Sbb(a,d,e,f,h){a.a={};a.a.id=e;a.a.ab=0;a.a.Bd=0;a.a.channel=0;a.a.Zb=0;a.a.dd=0;a.a.state=0;a.a.mode=f;a.a.video=h;a.a.He=0;a.a.ze=0;a.a.ka=0;a.a.Vc=0;a.a.pc=0;a.a.rd=0;a.a.T=0;a.a.ec=0;a.a.jb=0;a.a.Ua=0;a.a.Ob=0;a.a.Bc=0;a.a.callee=0;a.a.Mc=0;a.a.Wb=0;a.a.Yd=0;a.a.xe=0;a.a.oc=0;a.a.fc=0;a.a.$b=0;a.a.Oc=0;a.a.vc=0;a.a.fb=0;a.a.ua=0;a.a.Qe=0;a.a.ja=0;a.a.C=null;a.a.Xc=0;a.a.$c=0;a.a.md=$Sy();a.a.da=d;a.a.timeout=a.m.od;1==f&&(a.a.timeout=a.m.Hb);$SY(a,2E3)}
function $SZ(a){a.Rb=null;a.bc=null;a.ob=null;a.a=null;a.C=null;a.zb=!0}function $S_(a,d){a.a&&(a.J&&clearTimeout(a.J),a.J=null,console.log(a.a.C),a.a.C&&(a.a.C.S(),a.a.C=null),0<d&&$SX(a,d),$SZ(a))}function $Scb(a,d,e){if(a.a){0==d&&(d=a.a.id);if(71!=e){if(a.a.Zb&64)return;a.a.Zb=e}null!=a.notify&&(1==e?$Sx(a.notify,"Mesibo_OnCall")&&a.notify.Mesibo_OnCall(d,a.a.da,a.a.video):$Sx(a.notify,"Mesibo_OnCallStatus")&&a.notify.Mesibo_OnCallStatus(d,e))}}function $SX(a,d){a.a&&$Scb(a,a.a.id,d)}
function $Sdb(a){var d=new $SM(0);$SR(d,1,a.id,4);$SR(d,2,a.status,2);a.hasOwnProperty("type")&&$SR(d,3,a.type,2);a.hasOwnProperty("flag")&&$SR(d,4,a.o,4);a.hasOwnProperty("to_keepalive")&&$SR(d,7,a.kb,4);a.hasOwnProperty("to_answer")&&$SR(d,8,a.Wa,4);a.hasOwnProperty("to_request")&&$SR(d,9,a.lb,4);a.hasOwnProperty("sdp")&&$SU(d,5,a.sdp);a.hasOwnProperty("message")&&$SU(d,16,a.message);a.hasOwnProperty("tn")&&$ST(d,18,a.Oe,0);$SR(d,0,0,1);return $SO(d)}
function $Seb(a,d,e){var f={};f.id=d;f.status=e;f.o=0;e={};e.id=a.random();e.Mb=60;e.o=1049101;e.O=d;e.channel=128;f=$Sdb(f);a.V(e,d,f)}$S=$SW.prototype;
$S.W=function(a,d,e,f,h){!d&&this.a&&(d=this.a.da);!a&&this.a&&(a=this.a.id);if(!d||this.a.dd&64)return-1;var l={};l.id=a;l.status=e;f&&(l.sdp=f);l.flag=h|16;this.a.timeout=this.m.Hb;a={};this.a.ab=this.random();a.id=this.a.ab;a.Mb=30;e&64&&(a.Mb=60);a.o=1049101;a.O=this.a.id;a.channel=128;a.da=d;1==e?(l.kb=this.m.Hb,l.Wa=this.m.Wa,l.lb=this.m.lb,this.a.timeout=this.m.od):67==e?this.m.Ad&&this.a.ka&&(l.o|=8):3==l.status?this.a.Vc=1:5==l.status&&(this.a.ka=1);if(1==l.status||5==l.status)l.o|=1,this.a.video&&
(l.o|=2),this.m.lc&2&&(l.o|=131072),this.m.lc&1&&(l.o|=65536),this.m.lc&32&&(l.o|=262144),l.o|=524288;this.a.state=1;this.a.fc=$Sy();this.a.dd=e;d=$Sdb(l);return this.V(a,a.id,d)};$S.ie=function(a){this.a&&0!=this.a.mode||$SZ(this);if(!a)return!1;this.ob=a;return $Sfb(this,!1)};$S.he=function(a,d,e){this.a&&0!=this.a.mode||$SZ(this);if(!a||!d)return!1;this.Rb=a;this.bc=d;return e?$Sfb(this,!0):!0};
function $Sgb(a){a.Zc||(a.Zc=1,"undefined"===typeof adapter&&(a=document.createElement("script"),a.type="application/javascript",a.src="https://webrtc.github.io/adapter/adapter-latest.js",document.body?document.body.appendChild(a):console.log("document body missing")))}function $Sfb(a,d){$Sgb(a);if(a.C)return!0;a.C=new $S3a(a);d?a.C.La(a.Rb,a.bc):a.C.La(null,a.ob);a.zb=$S8a(a.C,d);return a.zb}
$S.call=function(a){if(this.Rb||this.bc||this.ob){var d=!0;this.ob&&(d=!1);if(d&&this.zc&8||this.zc&2)return $SX(this,74),-1;if(this.a)return $SX(this,71),-1;$Sbb(this,a,this.random(),0,d);$Shb(this,d?0:1);return this.W(this.a.id,null,1,null,4)}console.log("call is not set up, user setupVoiceCall or setupVideoCall first")};
$S.answer=function(a){if(!this.a)return-1;this.a.video&&a||(this.a.video=0);this.a.ka=1;this.a.ua=$Sy();this.a.oc=this.a.ua;a=0;if(this.a.jb)a=this.W(this.a.id,null,5,null,0);else if(this.a.ec=1,0!=$Sib(this,null))return this.W(this.a.id,null,72,null,0),$S_(this,72),0;$S0(this,1,0,1,this.a.video?0:1);return a};function $S4a(a,d,e,f){if(!a.a||!a.a)return-1;var h=e;a.a.Ob=f;0>e&&(e=65,1==a.a.mode&&(e=67),a.a.ka&&(e=64));d=a.W(d,null,e,null,0);$S_(a,0<h?h:64);return d}
$S.S=function(a){return $S4a(this,a,-1,1)};function $S0(a,d,e,f,h){if(!a.a)return-1;if(!a.a.ka)return 0;0==e&&d&&(a.a.pc||a.a.T)&&(d=0);0==h&&f&&(a.a.rd||a.a.T)&&(f=0);if(a.a.C){var l=0;d&&(a.a.Xc=e,l|=e?16:32);f&&(a.a.$c=h,l|=h?64:128);a.a.C.sa(l)}return 0}$S.sa=function(a,d,e){if(!this.a)return-1;if(!a&&!d)return 0;var f=0;a&&(f|=1);d&&(f|=2);this.W(this.a.id,null,e?9:10,null,f);a&&(this.a.pc=e);d&&(this.a.rd=e);return $S0(this,a,e,d,e)};
function $Sjb(a,d){if(!a.a)return-1;if(!a.a.ka)return $S4a(a,0,-1,0),0;var e=11;d||(e=12);var f=1;d&&a.a.T&5&&(f=0);d||a.a.T&5||(f=0);a.a.T=d?a.a.T|1:a.a.T&-2;f&&a.W(0,null,e,null,0);$S0(a,1,d,1,d);if(12==e&&a.a.T)return 0;$SX(a,e);return 0}$S.T=function(a){return $Sjb(this,a)};
function $SY(a,d){a.J&&clearTimeout(a.J);0>=d||(a.J=setTimeout(function(){a:if(a.a&&(a.J=null,!a.a.Wb||!a.a.ka)){var e=0;var f=$Sy();if(!a.a.Wb&&3==a.a.Ua&&(e=$SA(f,a.a.ua,a.m.me),0==e)){$S_(a,98);break a}if(a.a.ka&&3==a.a.Ua)$SY(a,e);else{0<a.a.fb&&(a.a.ja=$SA(f,a.a.fb,3E4),0==a.a.ja?a.a.fb=0:1500<a.a.ja&&(a.a.ja=1500));var h={};f=0==a.a.mode?$Skb(a,h):$Slb(a,h);h=h.status;0<h?$S_(a,h):0<e&&(0<f&&e<f||0==f)?$SY(a,e):$SY(a,f)}}},d))}
function $Skb(a,d){d.status=-1;var e=$Sy();if(1==a.a.state){e=$SA(e,a.a.fc,a.a.timeout);if(0==e){if(a.a.ja)return a.a.ja;d.status=68;return 0}return e}return 0==$SA(e,a.a.md,a.m.Wa)&&0==a.a.ja?(d.status=66,0):2==a.a.state?(e=$SA(e,a.a.vc,a.a.timeout),0==e?(a.W(a.a.id,null,6,null,0),a.a.timeout):e):a.a.ja}
function $Slb(a,d){d.status=-1;var e=$Sy();if(a.a.ja)return a.a.ja;if(1==a.a.state)return a=$SA(e,a.a.fc,a.a.timeout),0==a?(d.status=68,0):a;if(0==$SA(e,a.a.md,a.m.Wa))return d.status=65,0;a=$SA(e,a.a.$b,2*a.a.timeout);0==a&&(d.status=98);return a}function $Shb(a,d){if(a.a.C)return 0;if(!$Sfb(a)||!a.zb)return-1;a.a.C=a.C;if(!a.a.C)return-1;a.a.C.notify=a;var e=1;a.a.video&&(e|=2);d&&(e|=16,a.a.Xc=1,a.a.video&&(e|=64,a.a.$c=1));a.a.C.flags=e;return 0}
function $Sib(a,d){a.a.jb=1;a.a.Bc=0;d&&0!=d.length?(a.a.C.answer(0,d,a.a.video),a.a.Mc=0):(a.a.Mc=1,a.a.Bc=1,0<a.a.Oc||(a.a.Oc=$Sy(),a.a.C.call(a.a.video)));return 0}function $Smb(a){return a.u?"g:"+a.u:"a:"+a.address}function $Snb(a,d){a.Ja={};for(var e=0;e<d.length;e++){var f=d[e];f.w&&(a.ea.push(f),f.na.tc=$SD(f.w));a.Ja[$Smb(f)]=f}a.ea.sort(function(h,l){return h.w<l.w?1:h.w>l.w?-1:0})}
function $SUa(a,d){if(a.db&&(d.groupid=$SE(d.groupid),""!=d.address||0!=d.groupid)){var e={};e.address=d.address;e.groupid=d.groupid;e.picture=d.picture;e.name=d.name;e.lastMessage=d.lastMessage;e.ts=d.ts;e.picture==a.uc&&(e.picture="");e.name==e.address&&(e.name="");a.db&&$SOa(a.db,e)}}
$S.gd=function(a){a.u=$SE(a.u);if(0<a.u||$SB(a.address))a.address="";if(0==a.u&&""==a.address)return!1;a.w=0;a:{$SB(a.address)&&(a.address="");$SB(a.u)&&(a.u=0);$SB(a.name)&&(a.name="");$SB(a.Ra)&&(a.Ra="");$SB(a.na)&&(a.na=null);$SB(a.w)&&(a.w=0);a.u=$SE(a.u);var d=$Smb(a),e=this.Ja[d];if(e){e.name=a.name;e.Ra=a.Ra;var f=1;a.w>e.w&&(e.w=a.w,f=1);if(!f)break a}else e=a;this.Ja[d]=e;$SUa(this,e)}return a};
$S.sb=function(a,d){0<d&&(a="");a={address:a,u:d};(d=this.Ja[$Smb(a)])||(d=this.gd(a));$SB(d.Ra)&&(d.Ra=this.uc);$SB(d.name)&&(d.u?d.name="Group "+d.u:d.name=d.address);return d};function $Sob(a,d){for(var e=0;e<a.Ca.length;e++)if(a.Ca[e]==d)return;a.Ca.push(d)}function $S1(a,d,e,f,h){this.i=a;this.id=this.i.random();this.address=d;this.u=$SE(e);0<this.u&&(this.address="");this.za=h;this.R=[];this.reset();d||e||f||(this.summary=!0)}$S=$S1.prototype;
$S.reset=function(){this.position=0;this.R.length=0;this.summary=this.Ea=this.end=!1;this.ba=null;this.Fc=this.Gc=0};$S.stop=function(){$Spb(this.i,this,!1);this.Ea&&this.Lb(!1);this.reset();this.i.jc==this&&(this.i.jc=null)};$S.Lb=function(a,d){(this.Ea=a)&&d&&this.ba&&$SWa(this,this.ba)};$S.Gd=function(a){this.Ea=!1;this.summary=a;this.i.jc=this};function $SWa(a,d){!a.Ea||!d||18!=d.status||d.ts<a.Gc||0<d.groupid||!(d.flag&2)||0==d.id||(a.Gc=d.ts,a.i.bd({peer:d.peer,groupid:0},d.id),a.ba=null)}
function $SVa(a,d){return a.summary?!1:0<a.u||0<d.groupid?a.u==d.groupid:a.address==d.peer}
$S.read=function(a){$Spb(this.i,this,!this.summary);0==a&&(a=this.Fc);if(this.end)return this.za&&this.za(0),!1;if(this.summary)return this.R=this.i.ea,this.za(this.i.ea.length),this.i.db&&!this.i.db.ready&&this.i.Ca.push(this),!0;if(!this.i.db)return this.za&&this.za(0),!0;this.Fc=a;if(!this.i.db.ready)return $Sob(this.i,this),!0;var d=this;this.ba=null;this.Qb=0;this.i.db.read(this.address,this.u,this.position,a,function(e){if(null==e)d.Qb||(d.end=!0),$SWa(d,d.ba),d.za&&d.za(this.Qb);else{e.origin=
1;var f=e.status;$STa(d.i,e);if(18==f&&d.Ea){if(!d.ba||e.w>d.ba.w)d.ba=e;e.status=19;$SV(d.i.db,e.id,e.peer,e.groupid,19);e.status=18}this.position++;this.Qb++}});return!0};$S.Ld=function(){return this.summary?this.i.ea:this.R};window.ReadSession=$S1;$S1.prototype.enableReadReceipt=$S1.prototype.Lb;$S1.prototype.enableSummary=$S1.prototype.Gd;$S1.prototype.read=$S1.prototype.read;$S1.prototype.reset=$S1.prototype.reset;$S1.prototype.stop=$S1.prototype.stop;$S1.prototype.getMessages=$S1.prototype.Ld;
function $SW(){this.kc=this.uid=0;this.Ib="";this.qd="javascript";this.db=null;this.N="mesibo";this.Ca=[];this.jc=null;this.qa=this.ta=0;this.Dc=3E4;this.Ac=50;this.mc=0;this.Sb=604800;this.stopped=this.D=this.zc=0;this.j=new $Sra;this.yb=-1;this.notify=null;this.l={};this.Ya={};this.aa=null;this.$a=0;this.ma=-1;this.g=15E3;this.gb=0;this.Lc=this.ca=null;this.Tc=new $SL;this.Hd=parseInt(Math.floor(65535*Math.random()),10);this.Kc={};this.ea=[];this.Ja={};this.uc="";this.Fa=[];this.m={};this.m.lb=
6E4;this.m.Wa=6E4;this.m.od=15E3;this.m.Hb=7500;this.m.me=6E4;this.m.Ad=0;this.m.Ce=1;this.m.Pe=null;this.m.Ke=null;this.m.lc=0;this.m.Je=null;this.hb=this.m.Ie=0;$SZ(this);this.Zc=0;this.zb=!0;this.xa=-1;this.Y=null}function $Sqb(){}function $Srb(a,d,e){null!=a&&$Sx(a,"Mesibo_OnConnectionStatus")&&a.Mesibo_OnConnectionStatus(d,e)}function $S2(a,d,e){if(d!=a.xa){$Srb(a.notify,d,e);for(var f in a.l)$Srb(a.l[f],d,e);a.xa=d}}
function $Ssb(a,d){var e=a.notify;void 0!=d&&null!=d&&d.hasOwnProperty("channel")&&0<d.channel&&(d=d.channel,a.l.hasOwnProperty(d)&&(e=a.l[d]));return e}function $S3(a,d){var e=!0;!0===e?e=$Sqb:void 0===e&&(e=null);return(a=$Ssb(a,null))&&$Sx(a,d)?a[d]:e}
function $Stb(a,d){console.log("notify_message_status: "+d.da+":"+d.u);0<d.groupid&&(d.address="");var e=d,f=e.id,h=e.status,l=a.Kc[f];if(l){e=l;if(3==h)for(f in a.Fa){l=a.Fa[f];var m=e;if($SVa(l,m)){for(var v=l.R.length-1;0<=v;){if(l.R[v].id==m.id){l.R[v].status=3;$SV(l.i.db,m.id,m.peer,m.groupid,3);break}v--}if(!(0>=v))for(v--;0<=v&&2==l.R[v].status;)l.R[v].status=3,$SV(l.i.db,l.R[v].id,m.peer,m.groupid,3),v--}}e.status=h}(l=a.sb(e.peer,e.groupid))&&l.na&&l.na.id==f&&$SUa(a,l);a.db&&$SV(a.db,f,
e.peer,e.groupid,h);a=$Ssb(a,d);null!=a&&$Sx(a,"Mesibo_OnMessageStatus")&&a.Mesibo_OnMessageStatus(d)}$S=$SW.prototype;
$S.hd=function(a){if(39>a.length)return!1;this.D=this.uid=0;this.Ib=a;$SZa(this,this.Ib);if(0==this.uid)return!1;if(0!=this.uid)if(this.storage=new $SRa(this.uid),this.bb=this.storage.getItem("r_server",""),this.sd=this.storage.getItem("r_ports",""),this.ha=this.storage.getItem("r_lic",""),this.b=this.storage.getItem("r_expiry",0),a=$Sz(),0<this.b&&this.b>a){a=this.ha;for(var d=[],e=0;e<a.length;){var f=$SAa(a.charCodeAt(e++)),h=$SAa(a.charCodeAt(e++));d.push(16*f+h)}this.ha=d}else this.b=0,this.ha=
"";return!0};$S.ub=function(){return this.uid};$S.Jd=function(){return this.xa};$S.ic=function(a,d){void 0!=d&&0<d?this.l[d]=a:this.notify=a};$S.fd=function(a){this.qd=a};$S.hc=function(){var a=$Sz(),d="rtc.voicephp.com";0<this.b&&this.b>a?d=this.bb:(this.b=0,this.ha="");this.j.hc(1,d,5443)};
function $Sub(a,d,e){"indexedDB"in window?(a.db=new $SHa,a.db&&a.db.open(d,function(f){f?(console.log("getting contacts"),$SQa(a.db,function(h){console.log("ttt");console.log(h);$Snb(a,h);e()})):(console.log("opening db "+d+" failed"),this.db=null,e(null))})):e(null)}$S.de=function(a){this.N=a};function $Spb(a,d,e){e?a.Fa[d.id]=d:a.Fa.hasOwnProperty(d.id)&&delete a.Fa[d.id]}$S.Zd=function(a,d,e,f){console.log(this);void 0===a||null==a?a="":a=a.trim();return new $S1(this,a,d,e,f)};
$S.start=function(){if(0==this.uid)return $S2(this,4,0),!1;this.stopped=0;this.j.$=this;if(this.N&&0<this.N.length){var a=this;$Sub(this,this.N,function(){for(a.j.start();0<a.Ca.length;)a.Ca.shift().read(0),console.log("ps len "+a.Ca.length)});return 0}this.j.start();return!0};$S.stop=function(){this.stopped=1;this.j.stop()};$S.random=function(){return parseInt(Math.floor(2147483647*Math.random()))};function $Sua(a){a.hc();$S2(a,6,0)}
$S.Bb=function(){this.qa=0;this.ud=$Sy();0==this.uid&&$SZa(this,this.Ib);if(0==this.uid)this.D=1;else{var a=new $SM(0);a.H=1;a.result=1;a.id=1433999274;$SR(a,3,this.kc,4);$SR(a,6,1,1);this.send(a)}};$S.Tb=function(){3600<this.b&&(this.b-=3600,this.storage.setItem("r_expiry",this.b))};$S.Ab=function(){$Svb(this);return this.D||this.stopped?0:1};
$S.Ub=function(a){var d=new $SM(1);$SN(d,a.data,a.data.byteLength);0==d.b&&$SCa(d);a=d.result;switch(a){case 65:for(this.ta=d.tb();;){var e=$SP(d,0);if(null==e||0>=e.length)break;var f={},h=0,l=null;f.groupid=0;f.peer="";f.id=0;f.type=0;f.channel=0;f.ts=$Sy();for(var m in e){var v=e[m],w=v.val,x=v.data,D=v.len;v=parseInt(v.type,10);if(1!=v)switch(v){case 3:f.id=$SJ(x,x.byteLength);break;case 13:f.refid=$SJ(x,x.byteLength);break;case 6:f.groupid=w;f.gid=w;break;case 5:h=w;break;case 4:l=$SK(x,0,x.byteLength);
f.peer=l;break;case 7:f.message=x;f.mlen=D;break;case 16:f.ts=$Sy()-1E3*w;break;case 9:f.flag=w;break;case 10:f.channel=w;break;case 11:f.type=w;break;case 12:f.status=w}}0<h&&null!=l?(this.aa=this.Ya[h]=l,this.$a=h):0<h?(this.Ya.hasOwnProperty(h)?this.aa=l=this.Ya[h]:l=this.aa,this.$a=h,f.peer=l):f.peer=this.aa;f.origin=0;if(f.hasOwnProperty("status"))e=f,!this.a||0==e.id||128!=e.channel||!this.a||e.O&&this.a.id!=e.O?e=-1:(e.status&128?$S_(this,98):(2==e.status&&(this.a.fb=0,this.a.vc=$Sy(),this.a.state=
2,this.a.timeout=this.m.Hb),1==e.status&&0==this.a.Zb&&$SX(this,2)),e=0),0!=e&&$Stb(this,f);else if(f.hasOwnProperty("message")){f.hasOwnProperty("channel")||(f.channel=0);f.hasOwnProperty("id")||(f.id=0);if(256&parseInt(f.flag)&&(e=void 0,h=f,l=f.message,w=f.mlen,x=new $SM(1),$SN(x,l,w),l=$SP(x,1),h.message="",h.mlen=0,!(null==l||0>=l.length)))for(e in l)switch(w=l[e],x=w.val,D=w.data,v=w.len,parseInt(w.type,10)){case 1:h.title=$SK(D,0,D.byteLength-1);break;case 3:h.launchurl=$SK(D,0,D.byteLength-
1);break;case 6:x=$SJ(D,D.byteLength);w=(x&4294967295)/11930400-180;x=(x>>64)/11930400-90;h.lat=x;h.lon=w;break;case 16:h.filetype=x;break;case 17:h.filesize=x;break;case 18:h.fileflags=x;break;case 19:h.fileurl=$SK(D,0,D.byteLength-1);break;case 4:h.tn=D;break;case 20:h.rrid=$SJ(D,4<D.byteLength?4:D.byteLength);break;case 2:h.message=D;h.mlen=v;break;case 21:h.presence=x}f.data=f.message;f.datalen=f.mlen;f.message=$SK(f.message,0,f.mlen);if(f.hasOwnProperty("rrid"))f.status=3,f.id=f.rrid,f.rrid=
0,$Stb(this,f);else if(0==(f.flag&16)){if(4294967295>parseInt(f.id)&&0<parseInt(f.id)){e=f;h=f.id;l=this.$a;w=[];for(D=x=0;4>D;D++)w[x++]=h&255,h>>>=8;for(D=0;4>D&&(w[x++]=l&255,l>>>=8,0!=l);D++);l=w;w=0;x=[];for(h=0;h<l.length;h++)x[w++]=l[h]&15,x[w++]=l[h]>>4&15;h=$Swa(x,16,10);e.id=h}if(f.flag&512)a:{e=void 0;l=f.data;w=f.Ed;h={kb:0,o:0};x=new $SM(1);$SN(x,l,w);l=$SP(x,1);if(null==l||0>=l.length)e=null;else{for(e in l)switch(w=l[e],x=w.val,D=w.data,parseInt(w.type,10)){case 1:h.id=$SJ(D,D.byteLength)&
4294967295;break;case 2:h.status=x;break;case 3:h.type=x;break;case 4:h.o=x;break;case 7:h.kb=x;break;case 8:h.Wa=x;break;case 9:h.lb=x;break;case 5:h.sdp=$SK(D,0,D.byteLength),h.ae=h.sdp.length}0==h.kb&&(h.kb=6E4);e=h}h=f.da;this.a&&(this.a.fb=0);if(1!=e.status){if(!this.a){if(e.status&64)break a;$Seb(this,e.id,65);break a}if(0!=this.a.da.localeCompare(h))break a}1==e.status?this.a||0<this.hb?(f=67,0<this.hb&&(f=this.hb),$Seb(this,e.id,f),this.td(h,21,e.id,0,0,e.o&2?1:0)):parseInt($Sy()-f.Te)>e.lb?
this.td(h,21,e.id,0,0,e.o&2?1:0):($Sbb(this,h,e.id,1,e.o&2?1:0),this.a.$b=$Sy(),this.a.Bd=e.o,this.a.callee=1,this.W(this.a.id,h,3,null,e.o&4),$Scb(this,this.a.id,1),0!=$Shb(this,0)&&$S_(this,72)):(0<e.ae&&(this.a.Ua|=2,this.a.ua=$Sy()),this.a.$b=$Sy(),3==e.status?this.a.Vc=1:5==e.status&&(this.a.ua=$Sy(),this.a.oc=this.a.ua,this.a.ka=1,$S0(this,1,e.o&1?0:1,1,e.o&2?0:1)),5!=e.status||this.a.jb||0==$Sib(this,e.sdp)?8==e.status?this.a.jb?$Sab(this.a.C,e.sdp):0!=$Sib(this,e.sdp)&&(this.W(this.a.id,h,
72,null,0),$S_(this,72)):(11==e.status?(this.a.T|=2,$S0(this,1,1,1,1)):12==e.status&&(this.a.T&=-3,$S0(this,1,0,1,0)),12==e.status&&this.a.T||6==e.status||($Scb(this,this.a.id,e.status),e.status&64&&$S_(this,-1))):$S_(this,72))}else e=f,f=f.message,e.status=18,$STa(this,e),h=$Ssb(this,e),null!=h&&$Sx(h,"Mesibo_OnMessage")&&h.Mesibo_OnMessage(e,f)}}}break;case 79:$S2(this,3,0);this.stop();break;case 5:var F=d;$SP(F,0);$S_a(this,this.uid,F.tb(),this.cookie,F.map[10].data,this.qd);F=null;null!=F&&this.send(F);
return}if(a&128){$S4(this);if(145==a){F=$SP(d,0);if(!(null==F||0>=F.length)){for(var y in F)switch(d=F[y],a=d.val,m=d.data,parseInt(d.type,10)){case 7:this.bb=$SK(m,0,m.byteLength-1);break;case 8:this.sd=$SK(m,0,m.byteLength-1);break;case 3:this.b=$Sz()+a;break;case 4:this.ha=m.slice(0)}F=this.ha;y=this.ha.byteLength;d=[];for(a=0;a<0+y;a++)d.push((F[a]>>>4).toString(16)),d.push((F[a]&15).toString(16));F=d.join("");this.storage.setItem("r_server",this.bb);this.storage.setItem("r_ports",this.sd);this.storage.setItem("r_lic",
F);this.storage.setItem("r_expiry",this.b)}this.j.disconnect();this.j.start();return}if(192==(a&192)){$S2(this,4,0);this.qa=0;this.D=1;this.j.stop();return}}if(0==(a&64)){$S4(this);0==d.b&&$SCa(d);y=d.H;if(1==y){if(0==a){this.g=5*($Sy()-this.ud);5E3>this.g?this.g=5E3:3E4<this.g&&(this.g=3E4);this.qa=1;y=$SP(d,0);if(!(null==y||0>=y.length))for(F in y)if(a=y[F],d=a.val,a=parseInt(a.type,10),1!=a)switch(a){case 5:this.Dc=1E3*d;break;case 6:this.Ac=20*d;break;case 11:this.mc=d;break;case 13:this.Sb=d}$S0a(this);
$S2(this,1,this.mc);this.gb=0;this.ca=null;$SSa(this)}}else 2==y&&null!=this.ca&&(F={status:1},F.id=this.ca.ab,F.groupid=this.ca.Ka,F.peer="",0==F.groupid&&(F.peer=this.ca.Nb()),$Stb(this,F));this.gb=0;$SXa(this)}this.ta&&$S0a(this)};function $Svb(a){$S2a(a);$S4(a);a.gb=0;a.ca=null;$S2(a,2,0)}
$S.send=function(a){this.qa&&0<this.ta&&($SBa(a,this.ta),this.ta=0);if(!this.j)return 0;if(0!=a.mode)a=null;else{var d=0;a.buffer[d++]=a.H;a.buffer[d++]=a.result;var e=a.G-8;a.buffer[d++]=e&255;a.buffer[d++]=e>>8&255;$SBa(a,a.id);a=a.buffer.slice(0,a.G)}this.gb=1;this.j.send(a);this.qa&&$S0a(this);$Swb(this)};function $Swb(a){$S4(a);a.ma=setTimeout(function(){console.log("_response_timeout");a.j.disconnect();$Svb(a);a.j.start()},a.g)}function $S4(a){-1!=a.ma&&clearInterval(a.ma);a.ma=-1}
$S.Ud=function(){if(this.Y)return this.Y;$Sgb(this);return this.Y=new $S5(this)};window.performance=window.performance||{};performance.now=performance.now||performance.b||performance.g||performance.l||performance.webkitNow||Date.now;window.mesibo_exports=function(){var a=new $SW;a.fd("web");a.ic(null);a.hd(null);a.start();0(null,null,null);a.qe().Lb(!0)};window.Mesibo=$SW;$SW.prototype.start=$SW.prototype.start;$SW.prototype.stop=$SW.prototype.stop;$SW.prototype.setDatabase=$SW.prototype.de;
$SW.prototype.readDbSession=$SW.prototype.Zd;$SW.prototype.setListener=$SW.prototype.ic;$SW.prototype.setAppName=$SW.prototype.fd;$SW.prototype.setCredentials=$SW.prototype.hd;$SW.prototype.getUid=$SW.prototype.ub;$SW.prototype.getConnectionStatus=$SW.prototype.Jd;$SW.prototype.sendMessage=$SW.prototype.V;$SW.prototype.sendFile=$SW.prototype.vd;$SW.prototype.sendPresence=$SW.prototype.wd;$SW.prototype.sendReadReceipt=$SW.prototype.bd;$SW.prototype.setupVoiceCall=$SW.prototype.ie;
$SW.prototype.setupVideoCall=$SW.prototype.he;$SW.prototype.call=$SW.prototype.call;$SW.prototype.answer=$SW.prototype.answer;$SW.prototype.hangup=$SW.prototype.S;$SW.prototype.random=$SW.prototype.random;$SW.prototype.setContact=$SW.prototype.gd;$SW.prototype.getContact=$SW.prototype.sb;$SW.prototype.initGroupCall=$SW.prototype.Ud;$SW.prototype.time_msec=$Sy;$SW.prototype.time_sec=$Sz;$SW.prototype.convertTimestamp=$SD;window.array2String=$SK;
"https:"!=window.location.protocol&&window.location.host.replace(/(localhost|127\.0\.0\.1)(:\d+)?/i,"")&&(console.error("*** WARNING: mesibo requires secure(https) connection ***"),console.error("*** Detected host: "+window.location.host));function $Sxb(a,d,e,f){switch(d){case 3:a.type=e;break;case 5:a.sdp=$SK(f,0,f.byteLength);break;case 7:a.mid=$SK(f,0,f.byteLength);break;case 6:a.Fe=e}}
function $Syb(a,d,e){switch(d){case 3:a.width=e;break;case 4:a.height=e;break;case 5:a.rate=e;break;case 6:a.flags=e;break;case 7:a.codecs=e;break;case 8:a.F=e;break;case 13:a.Xa=e;break;case 9:a.pd=e;break;case 10:a.le=e;break;case 11:a.ad=e;break;case 12:a.c=e}}
function $Szb(a,d,e,f){switch(d){case 4:a.uid=e;break;case 7:a.da=e;break;case 6:a.wa=e;break;case 5:a.Ka=e;break;case 9:a.flags=e;break;case 10:a.codecs=e;break;case 14:a.Sa=e;break;case 15:a.Se=e;break;case 11:a.Da=e;break;case 12:a.Jb=e;break;case 16:a.Vd=e;break;case 17:a.role=e;break;case 13:a.name=$SK(f,0,f.byteLength);break;case 8:a.address=$SK(f,0,f.byteLength)}}function $S6(a,d,e,f){switch(d){case 5:a.id=$SJ(f,f.byteLength);break;case 3:a.H=e;break;case 19:a.error=e}}
function $S7(a){var d=new $SM(0);$SR(d,1,1,2);$SR(d,3,a.H,2);$SR(d,5,a.id,2);void 0!=a.w&&0<a.w&&$SR(d,10,a.w,8);if(void 0!=a.p&&null!=a.p){var e=a.p;$SR(d,20,1,1);$SR(d,7,e.da,1);$SR(d,11,e.Da,1);$SS(d,6,e.wa);$SS(d,5,e.Ka);$SS(d,10,e.codecs);$SS(d,12,e.se);$SS(d,9,e.flags);$SS(d,16,e.Vd);$SS(d,4,e.module);$SR(d,30,1,1)}void 0!=a.media&&null!=a.media&&(e=a.media,$SR(d,21,1,1),$SS(d,3,e.width),$SS(d,4,e.height),$SS(d,5,e.rate),$SS(d,6,e.flags),$SS(d,7,e.codecs),$SS(d,8,e.F),$SS(d,13,e.Xa),$SS(d,9,
e.pd),$SS(d,10,e.le),$SS(d,11,e.ad),$SS(d,12,e.c),e.nc&&$SU(d,17,e.nc),$SR(d,20,1,1));void 0!=a.sdp&&null!=a.sdp&&(e=a.be,a=a.sdp,$SR(d,23,1,1),$SS(d,3,e),$SU(d,5,a),$SR(d,10,1,1));$SR(d,2,1,1);return $SO(d)}function $S8(a){this.Z=a}$S8.prototype.b=function(a){this.xa=a;var d=this.Z,e=$Sy()-d.ke;1==a&&(2E3<e?$SAb(d):setTimeout(function(){$SAb(d)},2E3-e))};$S8.prototype.l=function(){};
$S8.prototype.g=function(a){a:{var d=this.Z;if(!(0<a.groupid&&a.groupid!=d.va)){var e=a.data,f=a.datalen,h=new $SM(1);$SN(h,e,f);e=$SP(h,1);f={Xb:[]};if(null==e||0>=e.length)var l=void 0;else{var m=$S6;h=f;var v=0;for(l in e){var w=e[l],x=w.val,D=w.data,F=w.len;w=parseInt(w.type,10);if(v||20!=w)if(20==v&&30==w)h.active=!1,h.role&1&&(h.active=!0),h.fa=!1,h.nd=!1,h.role&256&&(h.fa=!0,h.role&4096&&(h.nd=!0)),h.audio=!1,h.video=!1,h.flags&2&&(h.audio=!0),h.flags&4&&(h.video=!0),void 0==h.wa&&(h.wa=0),
f.Xb.push(h),m=$S6,h=f,v=0;else if(v||21!=w)if(21==v&&20==w)void 0==h.F&&(h.F=0),m=$S6,f.media=h,h=f,v=0;else if(v||23!=w)if(23==v&&10==w)m=$S6,f.Ma=h,h=f,v=0;else{if(2==w)break;m(h,w,x,D,F)}else v=w,m=$Sxb,h={};else v=w,m=$Syb,h={};else v=w,m=$Szb,h={}}l=f}if(0<l.Xb.length){e=l.Xb;f=d.i.ub();h=0;m=[];for(var y in e)if(v=e[y],D=v.uid,x=v.wa<<32|v.uid,0<v.da)$S3(d.i,"Mesibo_OnSubscriber")(v);else if(D==f)delete e[y];else if(v.fa)if(D=null,d.ga.hasOwnProperty(x)&&(D=d.ga[x]),v.active){if(D){if(D.update(v)){$S3(d.i,
"Mesibo_OnParticipantUpdated")(d.ga,D);continue}delete d.ga[x]}D=new $S9(d,v,!1);d.ga[x]=D;m.push(D);h++}else D&&D.K.Sa==v.Sa&&(D.S(!0),delete d.ga[x]);0<m.length&&$S3(d.i,"Mesibo_OnParticipants")(d.ga,m);if(0==l.id||void 0==l.O||0==l.O)break a}if(!(0<a.groupid)&&(a=a.refid,y=$So(d.pa,a,null)))if(9==l.H)l={H:9},l.id=y.O,a=$S7(l),d.V(y,a);else if(y.O!=l.id&&(y.O=l.id,d.pa[l.id]=y,delete d.pa[a]),2==l.H)a=d.Wc,d=d.Uc,y.oa=l.media,y.F=y.oa.F,y.B=y.B&&y.oa.flags&4?!0:!1,y.A=y.A&&y.oa.flags&2?!0:!1,y.c=
new $Sv(a,d),y.media={video:{source:y.source,F:y.oa.F,send:y.B,I:!1},audio:{send:y.A,I:!1}},y.media.ib=y.ib&&y.oa.flags&512?!0:!1,y.c.createOffer(y.media,y);else if(3==l.H)if(a={},a.sdp=l.Ma.sdp,1==l.Ma.type){a.type="offer";if(void 0==y.c||null==y.c)y.c=new $Sv(d.Wc,d.Uc);y.media={video:{I:y.B,send:!1},audio:{I:y.A,send:!1}};y.c.createAnswer(y.media,a,y)}else if(2==l.Ma.type)a.type="answer",y.c&&y.c.fe(a),l.media&&$SBb(y,l.media);else{if(3==l.Ma.type){d=null;if(20<l.Ma.sdp.length)try{d=JSON.parse(l.Ma.sdp)}catch(M){break a}y.c.Oa(d)}}else 4==
l.H&&(console.log("set"),$SBb(y,l.media)),19==l.H&&$S3(d.i,"Mesibo_OnError")(l.error)}}};$S8.prototype.Mesibo_OnMessage=$S8.prototype.g;$S8.prototype.Mesibo_OnMessageStatus=$S8.prototype.l;$S8.prototype.Mesibo_OnConnectionStatus=$S8.prototype.b;
function $SCb(a,d,e,f){f&&(a.Fb=!0);a={};if(f=e.getVideoTracks()[0])try{var h=0,l=0,m=0,v=0,w=f.getSettings();w&&(h=$So(w,"width",0),l=$So(w,"height",0),m=$So(w,"frameRate",0),w.hasOwnProperty("cursor")&&(v=1),a.width=h,a.height=l,a.rate=m,a.screen=v)}catch(x){}d.Jc=a;d.stream=e;e=e.getVideoTracks();null!==e&&void 0!==e&&0<e.length&&(d.vb=!0);d.v?d.nb(d.v):d.Yb&&d.nb(d.Yb);d.Pc(d)}
function $S5(a){$Ska();this.ke=$Sy();this.i=a;this.pa={};this.ga={};this.Wc={};this.va=0;this.Wd=5;this.Fb=!1;var d=this;this.Uc={L:function(e,f){e=e.la();e.Gb||e.S(!0);console.error("on error");console.error(f)},M:function(e,f){$S3(d.i,"Mesibo_OnPermission")(f)},Eb:function(e,f){e.la().Gb=f;$S3(d.i,"Mesibo_OnLocalMedia")(f)},Vb:function(){},Db:function(e,f){e=e.la();$SDb(e,f);e.fa&&"completed"!==f&&"connected"!==f?e.Ba(e,50):"connected"===f&&e.Ba(e,48)},cb:function(e,f,h){e=e.la();h?$SCb(d,e,f,!0):
e.Ba(e,65)},Aa:function(e,f,h){h&&$SCb(d,e.la(),f,!1)},Cb:function(){console.log("on webrtc cleanup")},ve:function(){},Qa:function(e,f){e=e.la();var h=2;"offer"==f.type&&(h=1);$SEb(e,h,f.sdp)},Oa:function(e,f){$SEb(e.la(),3,f?f.candidate:"eoc")},Kb:function(){},De:this};this.i.ic(new $S8(this),144);this.xa=a.xa;$Sqa(function(){for(var e in d.pa)d.pa[e].S()})}$S=$S5.prototype;$S.ge=function(a){void 0==a||null==a?this.va=0:(this.va=a,1==this.xa&&$SAb(this))};$S.Td=function(){this.va=0};
function $SAb(a){if(0!=a.va){var d=0;for(f in a.ga){var e=a.ga[f];e.K.Sa>d&&(d=e.K.Sa)}var f=new $SM(0);$SR(f,1,1,2);$SR(f,3,10,2);0<d&&$SR(f,10,d,8);$SR(f,2,1,2);d=$SO(f);f=a.i.random();e={};e.groupid=a.va;e.channel=144;e.type=21;e.refid=0;e.expiry=60;e.flag=1028;a.i.V(e,f,d)}}
$S.V=function(a,d,e){e&&void 0!=e&&null!=e&&0!=e||(e=this.i.random());if(void 0==a||null==a)a={},a.id=this.i.ub(),a.u=this.va,a.O=0;var f={};f.groupid=a.K.Ka;f.channel=144;f.type=21;f.refid=a.O;f.expiry=5;f.flag=1028;this.i.V(f,e,d)};$S.Kd=function(a,d,e,f){var h={};h.Ka=this.va;h.uid=this.i.ub();h.name=d;h.address=e;h.Da=0;h.wa=a;void 0!=f&&(h.Da=f);return new $S9(this,h,!0)};$S.Nd=function(){return this.ga};$S5.prototype.setRoom=$S5.prototype.ge;$S5.prototype.leaveRoom=$S5.prototype.Td;
$S5.prototype.getLocalParticipant=$S5.prototype.Kd;$S5.prototype.getParticipants=$S5.prototype.Nd;function $S9(a,d,e){this.Z=a;this.K=d;this.fa=e;this.Ba=this.Pc=null;this.B=this.A=!0;this.source=1;this.F=3;this.stream=null;this.La()}$S=$S9.prototype;
$S.La=function(){this.eb=this.Yb=this.v=null;this.ib=!0;this.Pb=this.vb=!1;this.Jc=this.codecs=this.media=this.c=null;this.width=0;this.v=null;this.media={video:{source:this.source,send:this.B,I:!1,replace:!0},audio:{send:this.A,I:!1,s:!0}};this.Gb=null;this.Ia=!1;this.qb=null;this.Jb=this.cc=0;this.oa=null;this.Ec=0};$S.update=function(a){if(a.Sa>this.K.Sa)return this.S(),!1;this.K=a;return!0};$S.tb=function(){return this.K.uid};$S.Id=function(){return this.O};$S.Nb=function(){return this.K.address};
$S.Md=function(){return this.K.name};$S.Qd=function(){return this.K.wa};$S.vb=function(){return this.vb};$S.Pb=function(){return this.Pb};$S.Cc=function(){return this.fa};$S.Sd=function(){return this.K.nd};function $SFb(a,d){if(!a.Z.Fb)try{var e=d.play();void 0===e||e.Be||e.then(function(){a.Z.Fb=!0},function(){console.log("rejected");a.Z.Fb=!1;this.Ba(this,59)}).catch(function(){})}catch(f){}}
$S.nb=function(a,d,e,f){console.log("attach: invoked on uid "+this.K.uid+", element: "+a);if(void 0==a||null==a)return!1;if(void 0==d||null==d)d=function(){};if("object"!==typeof a){var h=a;a=document.getElementById(a);if(!a){if(void 0===e||null===e)e=100;if(void 0===f||null===f||100<f)f=50;if(this.stream&&0<e&&0<f){console.log("attach ("+h+"): no element found, trying after "+e+"ms");var l=this;setTimeout(function(){l.nb(h,d,e,f-1)},e);return!0}console.log("attach ("+h+"): giving up, failed");d(!1);
return!1}}this.stream?(this.v==a&&this.v.srcObject==this.stream?console.log("attach ("+a.id+"): this stream already attached"):this.v&&this.v!=a?(console.log("attach ("+a.id+"): replacing existing player: "+this.v.id+" -> "+a.id),$Sna(a,this.v),this.v=a):(this.v=a,a.addEventListener("playing",function(){},!0),console.log("attach ("+a.id+"):attaching stream"),$Sma(this.v,this.stream),$SFb(this,this.v)),d(!0),$SGb(this)):(this.v=a,console.log("attach ("+a.id+"):no stream"),d(!1))};$S.xd=function(){$SGb(this)};
function $S$(a){return a.v?a.v.clientWidth:0}function $SHb(a,d,e){var f=a.Z,h={},l=0,m=0,v=0,w;for(w in f.pa){var x=f.pa[w];x.Cc()?v++:(l+=$S$(x),m++)}h.pd=l;h.ad=m;h.c=v;h.width=$S$(a);h.height=a.v?a.v.clientHeight:0;h.flags=a.media.video&&2==a.media.video.source?h.flags|256:h.flags&-257;h.Re=e;d.media=h}
$S.call=function(a,d,e,f){void 0==a&&(a={});if(this.Ia&&!this.Gb)this.S(1);else if(this.Ia)return this.fa?(this.source=$So(a,"source",this.source),this.qc(this.source)):!1;this.Yb=d;"object"!==typeof d?this.v=document.getElementById(d):this.v=d;this.Pc=e;this.Ba=f;this.A=$So(a,"audio",this.A);this.B=$So(a,"video",this.B);this.source=$So(a,"source",this.source);this.F=$So(a,"resolution",this.F);this.K.Da=$So(a,"pin",this.K.Da);this.Jb=$So(a,"adminpin",this.Jb);this.w=0;$SIb(this)};
function $SIb(a){a.S();if(!(a.cc>a.Z.Wd)){a.cc++;a.O=a.Z.i.random()+4294967296;var d={H:1},e={};e.da=a.K.uid;e.wa=a.K.wa;e.Da=a.K.Da;e.flags=7;d.p=e;a.fa?(d.media={},d.media.nc=navigator.userAgent):$SHb(a,d,0);d=$S7(d);a.Ia=!0;a.Gb=null;e=a.Z;e.pa[a.O]=a;e.V(a,d,void 0)}}
function $SEb(a,d,e){var f={H:3};f.id=a.O;if(a.fa){var h={flags:1};a.B&&(h.flags|=4);a.A&&(h.flags|=2);f.p=h}3!=d&&(f.media=a.Jc,f.media?f.media.flags=a.media.video&&2==a.media.video.source?f.media.flags|256:f.media.flags&-257:console.log("media is null "+d));f.sdp=e;f.be=d;d=$S7(f);a.Z.V(a,d)}
$S.qc=function(a){if(!a||!this.fa||!this.Ia)return!1;this.B=this.oa.flags&4?!0:!1;if(!this.B)return!1;var d=this.media.video.source;this.media={video:{source:a,F:this.F,send:this.B,I:!1,replace:!0},audio:{send:this.A,I:!1,s:!0}};this.A||(this.media.audio.remove=!0);this.c.createOffer(this.media,this);return d};function $SDb(a,d){"connected"!=d&&"completed"!=d?a.qb||(a.qb=setTimeout(function(){$SIb(a)},1E4)):"connected"==d&&(clearTimeout(a.qb),a.qb=null,a.cc=0)}
function $SJb(a,d,e){var f={H:4};f.id=a.O;e&&(e={flags:1},a.B&&(e.flags|=4),a.A&&(e.flags|=2),f.p=e);d&&$SHb(a,f,1);d=$S7(f);a.Z.V(a,d)}function $SGb(a){a.fa||(0==$S$(a)?setTimeout(function(){$SGb(a)},100):a.Ec!=$S$(a)&&(a.Ec=$S$(a),$SJb(a,!0,!1)))}
function $SBb(a,d){if(d.Xa||d.width){var e=a.c.Pd();if(e){var f=e.track.getSettings().width,h=e.getParameters();h.encodings||(h.encodings=[{}]);d.Xa&&0<d.Xa&&(h.encodings[0].maxBitrate=d.Xa);h.encodings[0].scaleResolutionDownBy=a.media.video&&d.width&&2!=a.media.video.source?Math.max(f/d.width,1):1;a.media.video&&2==a.media.video.source&&(h.encodings[0].scaleResolutionDownBy=1,h.encodings[0].maxBitrate=4096E3);try{e.setParameters(h)}catch(l){}}}}
$S.S=function(a){if(!this.Ia)return!1;this.c&&(this.c.S(),this.c=null);this.Ia=!1;this.v&&(this.v.srcObject=null);if(void 0==a||!a){var d={H:5};d.id=this.O;d=$S7(d);this.Z.V(this,d,0,!0)}a&&this.Ba&&this.Ba(this,64);this.La()};
$S.sa=function(a,d){if(a){if(this.B!=d)return;this.B=!d}else{if(this.A!=d)return;this.A=!d}this.fa?(this.B=this.B&&this.oa.flags&4?!0:!1,this.A=this.A&&this.oa.flags&2?!0:!1,this.c.sa(a,a?!this.B:!this.A),1!=this.media.video.source?$SJb(this,!1,!0):(this.media.video?this.media={video:{source:this.media.video.source,F:this.F,send:this.B,I:!1},audio:{send:this.A,I:!1}}:this.media={video:!1,audio:{send:this.A,I:!1}},a?this.media.video&&!this.B&&(this.media.video.remove=!0):this.A||(this.media.audio.remove=
!0),this.c.createOffer(this.media,this))):$SJb(this,!1,!0)};$S.Xd=function(a,d){return void 0!=d&&d?a?!this.K.video:!this.K.audio:a?!this.B:!this.A};$S.ne=function(a){if(a)return this.sa(a,this.B),!this.B;this.sa(a,this.A);return!this.A};$S.ee=function(a){this.eb=a};$S.la=function(){return this.eb};$S.Od=function(){return this.v};window.MesiboParticipant=$S9;$S9.prototype.getId=$S9.prototype.tb;$S9.prototype.getCallId=$S9.prototype.Id;$S9.prototype.getAddress=$S9.prototype.Nb;
$S9.prototype.getName=$S9.prototype.Md;$S9.prototype.hasVideo=$S9.prototype.vb;$S9.prototype.hasAudio=$S9.prototype.Pb;$S9.prototype.isLocal=$S9.prototype.Cc;$S9.prototype.isTalking=$S9.prototype.Sd;$S9.prototype.attach=$S9.prototype.nb;$S9.prototype.fullScreen=$S9.prototype.xd;$S9.prototype.call=$S9.prototype.call;$S9.prototype.mute=$S9.prototype.sa;$S9.prototype.toggleMute=$S9.prototype.ne;$S9.prototype.muteStatus=$S9.prototype.Xd;$S9.prototype.changeSource=$S9.prototype.qc;
$S9.prototype.hangup=$S9.prototype.S;$S9.prototype.setOpaque=$S9.prototype.ee;$S9.prototype.getOpaque=$S9.prototype.la;$S9.prototype.getPlayer=$S9.prototype.Od;$S9.prototype.getType=$S9.prototype.Qd;$S9.prototype.init=$S9.prototype.La;$S=$SW.prototype;$S.H=0;$S.result=0;$S.error=0;$S.name=0;$S.email=0;$S.password=0;$S.phone=0;$S.type=0;$S.uid=0;$S.o=0;$S.country=0;$S.na=0;$S.cookie=0;$S.K=0;$S.Ja=0;$S.Ib=0;$S.ptime=0;$S.amount=0;$S.currency=0;$S.status=0;$S.da=0;$S.address=0;$S.Ra=0;$S.id=0;$S.image=0;$S.rate=0;$S.channel=0;$S.Mb=0;$S.O=0;$S.message=0;$S.u=0;$S.w=0;$S.R=0;$S.R=0;$S.data=0;$S.Ed=0;$S.tc=0;$S1.prototype.R=0;$SW.prototype.appId=0;$SW.prototype.R=0;$S1.prototype.R=0;Navigator.prototype.mozGetUserMedia=function(){};
const MESIBO_FLAG_DELIVERYRECEIPT   = 0x1;
const MESIBO_FLAG_READRECEIPT   = 0x2;
const MESIBO_FLAG_TRANSIENT = 0x4;
const MESIBO_FLAG_FILETRANSFERRED = 0x10000;
const MESIBO_FLAG_FILEFAILED = 0x20000;
const MESIBO_FLAG_QUEUE = 0x40000;
const MESIBO_FLAG_NONBLOCKING = 0x80000;
//   protected final static int FLAG_DONTSEND = 0x200000;
const MESIBO_FLAG_EOR = 0x800000;


const MESIBO_FLAG_DEFAULT   = (MESIBO_FLAG_DELIVERYRECEIPT | MESIBO_FLAG_READRECEIPT);

const MESIBO_STATUS_UNKNOWN  = 0;
const MESIBO_STATUS_ONLINE  = 1;
const MESIBO_STATUS_OFFLINE = 2;
const MESIBO_STATUS_SIGNOUT = 3;
const MESIBO_STATUS_AUTHFAIL = 4;
const MESIBO_STATUS_STOPPED = 5;
const MESIBO_STATUS_CONNECTING = 6;
const MESIBO_STATUS_CONNECTFAILURE = 7;
const MESIBO_STATUS_NONETWORK = 8;
const MESIBO_STATUS_MANDUPDATE = 10;
const MESIBO_STATUS_SHUTDOWN = 20;
const MESIBO_STATUS_ACTIVITY = -1;

const MESIBO_MSGSTATUS_OUTBOX = 0;
const MESIBO_MSGSTATUS_SENT = 1;
const MESIBO_MSGSTATUS_DELIVERED = 2;
const MESIBO_MSGSTATUS_READ = 3;
const MESIBO_MSGSTATUS_RECEIVEDNEW =    0x12;
const MESIBO_MSGSTATUS_RECEIVEDREAD = 0x13;
const MESIBO_MSGSTATUS_FAIL = 0x80;
const MESIBO_MSGSTATUS_USEROFFLINE = 0x81;
const MESIBO_MSGSTATUS_INBOXFULL = 0x82;
const MESIBO_MSGSTATUS_INVALIDDEST = 0x83;
const MESIBO_MSGSTATUS_EXPIRED = 0x84;

const MESIBO_READFLAG_READRECEIPT = 1;
const MESIBO_READFLAG_SENDLAST    = 2;
const MESIBO_READFLAG_FIFO        = 4;
const MESIBO_READFLAG_SUMMARY    = 0x10;
const MESIBO_READFLAG_SENDEOR    = 0x20;
const MESIBO_READFLAG_WITHFILES    = 0x80;

const MESIBO_RESULT_OK = 0;
const MESIBO_RESULT_FAIL = 0x80;
const MESIBO_RESULT_GENERROR = 0x81;
const MESIBO_RESULT_NOSUCHUSER = 0x83;
const MESIBO_RESULT_INBOXFULL = 0x84;
const MESIBO_RESULT_BADREQ = 0x85;
const MESIBO_RESULT_OVERCAPACITY = 0x86;
const MESIBO_RESULT_RETRYLATER = 0x87;

const MESIBO_RESULT_TIMEOUT = 0xB0;
const MESIBO_RESULT_CONNECTFAIL = 0xB1;
const MESIBO_RESULT_DISCONNECTED = 0xB2;
const MESIBO_RESULT_REQINPROGRESS = 0xB3;
const MESIBO_RESULT_BUFFERFULL = 0xB4;

const MESIBO_RESULT_AUTHFAIL = 0xC0;
const MESIBO_RESULT_DENIED = 0xC1;

const MESIBO_ORIGIN_REALTIME = 0;
const MESIBO_ORIGIN_DBMESSAGE = 1;
const MESIBO_ORIGIN_DBSUMMARY = 2;
const MESIBO_ORIGIN_DBPENDING = 3;
const MESIBO_ORIGIN_FILTER = 4;
const MESIBO_ORIGIN_MESSAGESTATUS = 5;

//Activity 0-1000 reserved for Mesibo
const MESIBO_ACTIVITY_NONE = 0;
const MESIBO_ACTIVITY_ONLINE = 1;
const MESIBO_ACTIVITY_ONLINERESP = 2;
const MESIBO_ACTIVITY_TYPING = 3;
const MESIBO_ACTIVITY_TYPINGCLEARED = 4;
const MESIBO_ACTIVITY_JOINED = 10;
const MESIBO_ACTIVITY_LEFT = 11;

const MESIBO_CALLSTATUS_NONE                 = 0x00;
const MESIBO_CALLSTATUS_OFFER                = 0x01;
const MESIBO_CALLSTATUS_INPROGRESS           = 0x02;
const MESIBO_CALLSTATUS_RINGING              = 0x03;
const MESIBO_CALLSTATUS_ANSWER               = 0x05;
const MESIBO_CALLSTATUS_UPDATE               = 0x06;
const MESIBO_CALLSTATUS_DTMF                 = 0x07;
const MESIBO_CALLSTATUS_SDP                  = 0x08;
const MESIBO_CALLSTATUS_MUTE                 = 0x09;
const MESIBO_CALLSTATUS_UNMUTE               = 0x0A;
const MESIBO_CALLSTATUS_HOLD                 = 0x0B;
const MESIBO_CALLSTATUS_UNHOLD               = 0x0C;
const MESIBO_CALLSTATUS_PING                 = 0x21;
const MESIBO_CALLSTATUS_INFO                 = 0x23;
const MESIBO_CALLSTATUS_ECHO                 = 0x24;
const MESIBO_CALLSTATUS_REDIRECT             = 0x25;


// Phone Specific ERRORs
const MESIBO_CALLSTATUS_COMPLETE             = 0x40;
const MESIBO_CALLSTATUS_CANCEL               = 0x41;
const MESIBO_CALLSTATUS_NOANSWER             = 0x42;
const MESIBO_CALLSTATUS_BUSY                 = 0x43;
const MESIBO_CALLSTATUS_UNREACHABLE          = 0x44;
const MESIBO_CALLSTATUS_OFFLINE              = 0x45;
const MESIBO_CALLSTATUS_INVALIDDEST          = 0x46;
const MESIBO_CALLSTATUS_INVALIDSTATE         = 0x47;
const MESIBO_CALLSTATUS_NOCALLS              = 0x48;
const MESIBO_CALLSTATUS_NOVIDEOCALLS         = 0x49;
const MESIBO_CALLSTATUS_NOTALLOWED           = 0x4A;

//Local Status used by client
const MESIBO_CALLSTATUS_CHANNELUP            = 0x30;
const MESIBO_CALLSTATUS_QUALITY              = 0x31;
const MESIBO_CALLSTATUS_RECONNECTING         = 0x32;
const MESIBO_CALLSTATUS_SERVER               = 0x3A;

const MESIBO_CALLSTATUS_AUTHFAIL             = 0x50;
const MESIBO_CALLSTATUS_NOCREDITS            = 0x51;
const MESIBO_CALLSTATUS_NONTRINGMEDEST       = 0x52;
const MESIBO_CALLSTATUS_INCOMPATIBLE         = 0x53;
const MESIBO_CALLSTATUS_BADCALLID            = 0x54;

// Generic Errors
const MESIBO_CALLSTATUS_ERROR                = 0x60;
const MESIBO_CALLSTATUS_HWERROR              = 0x61;
const MESIBO_CALLSTATUS_NETWORKERROR         = 0x62;
const MESIBO_CALLSTATUS_NETWORKBLOCKED       = 0x63;


